/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AAtributosAtributos extends PAtributos
{
    private PDec _dec_;
    private PAtributos _atributos_;

    public AAtributosAtributos()
    {
        // Constructor
    }

    public AAtributosAtributos(
        @SuppressWarnings("hiding") PDec _dec_,
        @SuppressWarnings("hiding") PAtributos _atributos_)
    {
        // Constructor
        setDec(_dec_);

        setAtributos(_atributos_);

    }

    @Override
    public Object clone()
    {
        return new AAtributosAtributos(
            cloneNode(this._dec_),
            cloneNode(this._atributos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtributosAtributos(this);
    }

    public PDec getDec()
    {
        return this._dec_;
    }

    public void setDec(PDec node)
    {
        if(this._dec_ != null)
        {
            this._dec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dec_ = node;
    }

    public PAtributos getAtributos()
    {
        return this._atributos_;
    }

    public void setAtributos(PAtributos node)
    {
        if(this._atributos_ != null)
        {
            this._atributos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atributos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dec_)
            + toString(this._atributos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dec_ == child)
        {
            this._dec_ = null;
            return;
        }

        if(this._atributos_ == child)
        {
            this._atributos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dec_ == oldChild)
        {
            setDec((PDec) newChild);
            return;
        }

        if(this._atributos_ == oldChild)
        {
            setAtributos((PAtributos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
