/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class AAtribComando extends PComando
{
    private TId _id_;
    private TAtribuicao _atribuicao_;
    private PExp _exp_;
    private TPontoVirgula _ponto_virgula_;

    public AAtribComando ()
    {
    }

    public AAtribComando (
            TId _id_,
            TAtribuicao _atribuicao_,
            PExp _exp_,
            TPontoVirgula _ponto_virgula_
    )
    {
        setId (_id_);
        setAtribuicao (_atribuicao_);
        setExp (_exp_);
        setPontoVirgula (_ponto_virgula_);
    }

    public Object clone()
    {
        return new AAtribComando (
            (TId)cloneNode (_id_),
            (TAtribuicao)cloneNode (_atribuicao_),
            (PExp)cloneNode (_exp_),
            (TPontoVirgula)cloneNode (_ponto_virgula_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtribComando(this);
    }

    public TId getId ()
    {
        return _id_;
    }

    public void setId (TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }
    public TAtribuicao getAtribuicao ()
    {
        return _atribuicao_;
    }

    public void setAtribuicao (TAtribuicao node)
    {
        if(_atribuicao_ != null)
        {
            _atribuicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _atribuicao_ = node;
    }
    public PExp getExp ()
    {
        return _exp_;
    }

    public void setExp (PExp node)
    {
        if(_exp_ != null)
        {
            _exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exp_ = node;
    }
    public TPontoVirgula getPontoVirgula ()
    {
        return _ponto_virgula_;
    }

    public void setPontoVirgula (TPontoVirgula node)
    {
        if(_ponto_virgula_ != null)
        {
            _ponto_virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _ponto_virgula_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_id_)
            + toString (_atribuicao_)
            + toString (_exp_)
            + toString (_ponto_virgula_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _id_ == child )
        {
            _id_ = null;
            return;
        }
        if ( _atribuicao_ == child )
        {
            _atribuicao_ = null;
            return;
        }
        if ( _exp_ == child )
        {
            _exp_ = null;
            return;
        }
        if ( _ponto_virgula_ == child )
        {
            _ponto_virgula_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _id_ == oldChild )
        {
            setId ((TId) newChild);
            return;
        }
        if ( _atribuicao_ == oldChild )
        {
            setAtribuicao ((TAtribuicao) newChild);
            return;
        }
        if ( _exp_ == oldChild )
        {
            setExp ((PExp) newChild);
            return;
        }
        if ( _ponto_virgula_ == oldChild )
        {
            setPontoVirgula ((TPontoVirgula) newChild);
            return;
        }
    }

}
