/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class ABlocoExpBlocoExp extends PBlocoExp
{
    private TComeca _comeca_;
    private PListaDecCons _lista_dec_cons_;
    private PExp _exp_;
    private TTermina _termina_;

    public ABlocoExpBlocoExp ()
    {
    }

    public ABlocoExpBlocoExp (
            TComeca _comeca_,
            PListaDecCons _lista_dec_cons_,
            PExp _exp_,
            TTermina _termina_
    )
    {
        setComeca (_comeca_);
        setListaDecCons (_lista_dec_cons_);
        setExp (_exp_);
        setTermina (_termina_);
    }

    public Object clone()
    {
        return new ABlocoExpBlocoExp (
            (TComeca)cloneNode (_comeca_),
            (PListaDecCons)cloneNode (_lista_dec_cons_),
            (PExp)cloneNode (_exp_),
            (TTermina)cloneNode (_termina_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlocoExpBlocoExp(this);
    }

    public TComeca getComeca ()
    {
        return _comeca_;
    }

    public void setComeca (TComeca node)
    {
        if(_comeca_ != null)
        {
            _comeca_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comeca_ = node;
    }
    public PListaDecCons getListaDecCons ()
    {
        return _lista_dec_cons_;
    }

    public void setListaDecCons (PListaDecCons node)
    {
        if(_lista_dec_cons_ != null)
        {
            _lista_dec_cons_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lista_dec_cons_ = node;
    }
    public PExp getExp ()
    {
        return _exp_;
    }

    public void setExp (PExp node)
    {
        if(_exp_ != null)
        {
            _exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exp_ = node;
    }
    public TTermina getTermina ()
    {
        return _termina_;
    }

    public void setTermina (TTermina node)
    {
        if(_termina_ != null)
        {
            _termina_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _termina_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_comeca_)
            + toString (_lista_dec_cons_)
            + toString (_exp_)
            + toString (_termina_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _comeca_ == child )
        {
            _comeca_ = null;
            return;
        }
        if ( _lista_dec_cons_ == child )
        {
            _lista_dec_cons_ = null;
            return;
        }
        if ( _exp_ == child )
        {
            _exp_ = null;
            return;
        }
        if ( _termina_ == child )
        {
            _termina_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _comeca_ == oldChild )
        {
            setComeca ((TComeca) newChild);
            return;
        }
        if ( _lista_dec_cons_ == oldChild )
        {
            setListaDecCons ((PListaDecCons) newChild);
            return;
        }
        if ( _exp_ == oldChild )
        {
            setExp ((PExp) newChild);
            return;
        }
        if ( _termina_ == oldChild )
        {
            setTermina ((TTermina) newChild);
            return;
        }
    }

}
