/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class ACallComando extends PComando
{
    private PChamada _chamada_;
    private TPontoVirgula _ponto_virgula_;

    public ACallComando ()
    {
    }

    public ACallComando (
            PChamada _chamada_,
            TPontoVirgula _ponto_virgula_
    )
    {
        setChamada (_chamada_);
        setPontoVirgula (_ponto_virgula_);
    }

    public Object clone()
    {
        return new ACallComando (
            (PChamada)cloneNode (_chamada_),
            (TPontoVirgula)cloneNode (_ponto_virgula_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACallComando(this);
    }

    public PChamada getChamada ()
    {
        return _chamada_;
    }

    public void setChamada (PChamada node)
    {
        if(_chamada_ != null)
        {
            _chamada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _chamada_ = node;
    }
    public TPontoVirgula getPontoVirgula ()
    {
        return _ponto_virgula_;
    }

    public void setPontoVirgula (TPontoVirgula node)
    {
        if(_ponto_virgula_ != null)
        {
            _ponto_virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _ponto_virgula_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_chamada_)
            + toString (_ponto_virgula_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _chamada_ == child )
        {
            _chamada_ = null;
            return;
        }
        if ( _ponto_virgula_ == child )
        {
            _ponto_virgula_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _chamada_ == oldChild )
        {
            setChamada ((PChamada) newChild);
            return;
        }
        if ( _ponto_virgula_ == oldChild )
        {
            setPontoVirgula ((TPontoVirgula) newChild);
            return;
        }
    }

}
