/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AClasseListaClasse extends PListaClasse
{
    private PDefClasse _defClasse_;

    public AClasseListaClasse()
    {
        // Constructor
    }

    public AClasseListaClasse(
        @SuppressWarnings("hiding") PDefClasse _defClasse_)
    {
        // Constructor
        setDefClasse(_defClasse_);

    }

    @Override
    public Object clone()
    {
        return new AClasseListaClasse(
            cloneNode(this._defClasse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClasseListaClasse(this);
    }

    public PDefClasse getDefClasse()
    {
        return this._defClasse_;
    }

    public void setDefClasse(PDefClasse node)
    {
        if(this._defClasse_ != null)
        {
            this._defClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._defClasse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._defClasse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._defClasse_ == child)
        {
            this._defClasse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._defClasse_ == oldChild)
        {
            setDefClasse((PDefClasse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
