/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AContCondCondExp2 extends PCondExp2
{
    private PExp _exp_;
    private PCondExp3 _condExp3_;

    public AContCondCondExp2()
    {
        // Constructor
    }

    public AContCondCondExp2(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PCondExp3 _condExp3_)
    {
        // Constructor
        setExp(_exp_);

        setCondExp3(_condExp3_);

    }

    @Override
    public Object clone()
    {
        return new AContCondCondExp2(
            cloneNode(this._exp_),
            cloneNode(this._condExp3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAContCondCondExp2(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PCondExp3 getCondExp3()
    {
        return this._condExp3_;
    }

    public void setCondExp3(PCondExp3 node)
    {
        if(this._condExp3_ != null)
        {
            this._condExp3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condExp3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._condExp3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._condExp3_ == child)
        {
            this._condExp3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._condExp3_ == oldChild)
        {
            setCondExp3((PCondExp3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
