/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class ADecObjDecObj extends PDecObj
{
    private TObjeto _objeto_;
    private TCid _cid_;
    private PListaId _listaId_;
    private TPontoVirgula _pontoVirgula_;

    public ADecObjDecObj()
    {
        // Constructor
    }

    public ADecObjDecObj(
        @SuppressWarnings("hiding") TObjeto _objeto_,
        @SuppressWarnings("hiding") TCid _cid_,
        @SuppressWarnings("hiding") PListaId _listaId_,
        @SuppressWarnings("hiding") TPontoVirgula _pontoVirgula_)
    {
        // Constructor
        setObjeto(_objeto_);

        setCid(_cid_);

        setListaId(_listaId_);

        setPontoVirgula(_pontoVirgula_);

    }

    @Override
    public Object clone()
    {
        return new ADecObjDecObj(
            cloneNode(this._objeto_),
            cloneNode(this._cid_),
            cloneNode(this._listaId_),
            cloneNode(this._pontoVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecObjDecObj(this);
    }

    public TObjeto getObjeto()
    {
        return this._objeto_;
    }

    public void setObjeto(TObjeto node)
    {
        if(this._objeto_ != null)
        {
            this._objeto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._objeto_ = node;
    }

    public TCid getCid()
    {
        return this._cid_;
    }

    public void setCid(TCid node)
    {
        if(this._cid_ != null)
        {
            this._cid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cid_ = node;
    }

    public PListaId getListaId()
    {
        return this._listaId_;
    }

    public void setListaId(PListaId node)
    {
        if(this._listaId_ != null)
        {
            this._listaId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaId_ = node;
    }

    public TPontoVirgula getPontoVirgula()
    {
        return this._pontoVirgula_;
    }

    public void setPontoVirgula(TPontoVirgula node)
    {
        if(this._pontoVirgula_ != null)
        {
            this._pontoVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._objeto_)
            + toString(this._cid_)
            + toString(this._listaId_)
            + toString(this._pontoVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._objeto_ == child)
        {
            this._objeto_ = null;
            return;
        }

        if(this._cid_ == child)
        {
            this._cid_ = null;
            return;
        }

        if(this._listaId_ == child)
        {
            this._listaId_ = null;
            return;
        }

        if(this._pontoVirgula_ == child)
        {
            this._pontoVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._objeto_ == oldChild)
        {
            setObjeto((TObjeto) newChild);
            return;
        }

        if(this._cid_ == oldChild)
        {
            setCid((TCid) newChild);
            return;
        }

        if(this._listaId_ == oldChild)
        {
            setListaId((PListaId) newChild);
            return;
        }

        if(this._pontoVirgula_ == oldChild)
        {
            setPontoVirgula((TPontoVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
