/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class ADecCons extends PDecCons
{
    private TConstante _constante_;
    private PTipoPrimitivo _tipo_primitivo_;
    private PListaInicializacao _lista_inicializacao_;

    public ADecCons ()
    {
    }

    public ADecCons (
            TConstante _constante_,
            PTipoPrimitivo _tipo_primitivo_,
            PListaInicializacao _lista_inicializacao_
    )
    {
        setConstante (_constante_);
        setTipoPrimitivo (_tipo_primitivo_);
        setListaInicializacao (_lista_inicializacao_);
    }

    public Object clone()
    {
        return new ADecCons (
            (TConstante)cloneNode (_constante_),
            (PTipoPrimitivo)cloneNode (_tipo_primitivo_),
            (PListaInicializacao)cloneNode (_lista_inicializacao_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecCons(this);
    }

    public TConstante getConstante ()
    {
        return _constante_;
    }

    public void setConstante (TConstante node)
    {
        if(_constante_ != null)
        {
            _constante_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _constante_ = node;
    }
    public PTipoPrimitivo getTipoPrimitivo ()
    {
        return _tipo_primitivo_;
    }

    public void setTipoPrimitivo (PTipoPrimitivo node)
    {
        if(_tipo_primitivo_ != null)
        {
            _tipo_primitivo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tipo_primitivo_ = node;
    }
    public PListaInicializacao getListaInicializacao ()
    {
        return _lista_inicializacao_;
    }

    public void setListaInicializacao (PListaInicializacao node)
    {
        if(_lista_inicializacao_ != null)
        {
            _lista_inicializacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lista_inicializacao_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_constante_)
            + toString (_tipo_primitivo_)
            + toString (_lista_inicializacao_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _constante_ == child )
        {
            _constante_ = null;
            return;
        }
        if ( _tipo_primitivo_ == child )
        {
            _tipo_primitivo_ = null;
            return;
        }
        if ( _lista_inicializacao_ == child )
        {
            _lista_inicializacao_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _constante_ == oldChild )
        {
            setConstante ((TConstante) newChild);
            return;
        }
        if ( _tipo_primitivo_ == oldChild )
        {
            setTipoPrimitivo ((PTipoPrimitivo) newChild);
            return;
        }
        if ( _lista_inicializacao_ == oldChild )
        {
            setListaInicializacao ((PListaInicializacao) newChild);
            return;
        }
    }

}
