/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class ADecProcedimento extends PDecProcedimento
{
    private TPontoDeEntrada _ponto_de_entrada_;
    private TProcedimento _procedimento_;
    private TId _id_;
    private TParentesesEsquerdo _parenteses_esquerdo_;
    private PParametros _parametros_;
    private TParentesesDireito _parenteses_direito_;
    private PComando _comando_;

    public ADecProcedimento ()
    {
    }

    public ADecProcedimento (
            TPontoDeEntrada _ponto_de_entrada_,
            TProcedimento _procedimento_,
            TId _id_,
            TParentesesEsquerdo _parenteses_esquerdo_,
            PParametros _parametros_,
            TParentesesDireito _parenteses_direito_,
            PComando _comando_
    )
    {
        setPontoDeEntrada (_ponto_de_entrada_);
        setProcedimento (_procedimento_);
        setId (_id_);
        setParentesesEsquerdo (_parenteses_esquerdo_);
        setParametros (_parametros_);
        setParentesesDireito (_parenteses_direito_);
        setComando (_comando_);
    }

    public Object clone()
    {
        return new ADecProcedimento (
            (TPontoDeEntrada)cloneNode (_ponto_de_entrada_),
            (TProcedimento)cloneNode (_procedimento_),
            (TId)cloneNode (_id_),
            (TParentesesEsquerdo)cloneNode (_parenteses_esquerdo_),
            (PParametros)cloneNode (_parametros_),
            (TParentesesDireito)cloneNode (_parenteses_direito_),
            (PComando)cloneNode (_comando_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecProcedimento(this);
    }

    public TPontoDeEntrada getPontoDeEntrada ()
    {
        return _ponto_de_entrada_;
    }

    public void setPontoDeEntrada (TPontoDeEntrada node)
    {
        if(_ponto_de_entrada_ != null)
        {
            _ponto_de_entrada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _ponto_de_entrada_ = node;
    }
    public TProcedimento getProcedimento ()
    {
        return _procedimento_;
    }

    public void setProcedimento (TProcedimento node)
    {
        if(_procedimento_ != null)
        {
            _procedimento_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _procedimento_ = node;
    }
    public TId getId ()
    {
        return _id_;
    }

    public void setId (TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }
    public TParentesesEsquerdo getParentesesEsquerdo ()
    {
        return _parenteses_esquerdo_;
    }

    public void setParentesesEsquerdo (TParentesesEsquerdo node)
    {
        if(_parenteses_esquerdo_ != null)
        {
            _parenteses_esquerdo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _parenteses_esquerdo_ = node;
    }
    public PParametros getParametros ()
    {
        return _parametros_;
    }

    public void setParametros (PParametros node)
    {
        if(_parametros_ != null)
        {
            _parametros_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _parametros_ = node;
    }
    public TParentesesDireito getParentesesDireito ()
    {
        return _parenteses_direito_;
    }

    public void setParentesesDireito (TParentesesDireito node)
    {
        if(_parenteses_direito_ != null)
        {
            _parenteses_direito_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _parenteses_direito_ = node;
    }
    public PComando getComando ()
    {
        return _comando_;
    }

    public void setComando (PComando node)
    {
        if(_comando_ != null)
        {
            _comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comando_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_ponto_de_entrada_)
            + toString (_procedimento_)
            + toString (_id_)
            + toString (_parenteses_esquerdo_)
            + toString (_parametros_)
            + toString (_parenteses_direito_)
            + toString (_comando_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _ponto_de_entrada_ == child )
        {
            _ponto_de_entrada_ = null;
            return;
        }
        if ( _procedimento_ == child )
        {
            _procedimento_ = null;
            return;
        }
        if ( _id_ == child )
        {
            _id_ = null;
            return;
        }
        if ( _parenteses_esquerdo_ == child )
        {
            _parenteses_esquerdo_ = null;
            return;
        }
        if ( _parametros_ == child )
        {
            _parametros_ = null;
            return;
        }
        if ( _parenteses_direito_ == child )
        {
            _parenteses_direito_ = null;
            return;
        }
        if ( _comando_ == child )
        {
            _comando_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _ponto_de_entrada_ == oldChild )
        {
            setPontoDeEntrada ((TPontoDeEntrada) newChild);
            return;
        }
        if ( _procedimento_ == oldChild )
        {
            setProcedimento ((TProcedimento) newChild);
            return;
        }
        if ( _id_ == oldChild )
        {
            setId ((TId) newChild);
            return;
        }
        if ( _parenteses_esquerdo_ == oldChild )
        {
            setParentesesEsquerdo ((TParentesesEsquerdo) newChild);
            return;
        }
        if ( _parametros_ == oldChild )
        {
            setParametros ((PParametros) newChild);
            return;
        }
        if ( _parenteses_direito_ == oldChild )
        {
            setParentesesDireito ((TParentesesDireito) newChild);
            return;
        }
        if ( _comando_ == oldChild )
        {
            setComando ((PComando) newChild);
            return;
        }
    }

}
