/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class ADecVar extends PDecVar
{
    private TVariavel _variavel_;
    private PTipo _tipo_;
    private PListaId _lista_id_;
    private TPontoVirgula _ponto_virgula_;

    public ADecVar ()
    {
    }

    public ADecVar (
            TVariavel _variavel_,
            PTipo _tipo_,
            PListaId _lista_id_,
            TPontoVirgula _ponto_virgula_
    )
    {
        setVariavel (_variavel_);
        setTipo (_tipo_);
        setListaId (_lista_id_);
        setPontoVirgula (_ponto_virgula_);
    }

    public Object clone()
    {
        return new ADecVar (
            (TVariavel)cloneNode (_variavel_),
            (PTipo)cloneNode (_tipo_),
            (PListaId)cloneNode (_lista_id_),
            (TPontoVirgula)cloneNode (_ponto_virgula_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecVar(this);
    }

    public TVariavel getVariavel ()
    {
        return _variavel_;
    }

    public void setVariavel (TVariavel node)
    {
        if(_variavel_ != null)
        {
            _variavel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _variavel_ = node;
    }
    public PTipo getTipo ()
    {
        return _tipo_;
    }

    public void setTipo (PTipo node)
    {
        if(_tipo_ != null)
        {
            _tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tipo_ = node;
    }
    public PListaId getListaId ()
    {
        return _lista_id_;
    }

    public void setListaId (PListaId node)
    {
        if(_lista_id_ != null)
        {
            _lista_id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lista_id_ = node;
    }
    public TPontoVirgula getPontoVirgula ()
    {
        return _ponto_virgula_;
    }

    public void setPontoVirgula (TPontoVirgula node)
    {
        if(_ponto_virgula_ != null)
        {
            _ponto_virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _ponto_virgula_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_variavel_)
            + toString (_tipo_)
            + toString (_lista_id_)
            + toString (_ponto_virgula_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _variavel_ == child )
        {
            _variavel_ = null;
            return;
        }
        if ( _tipo_ == child )
        {
            _tipo_ = null;
            return;
        }
        if ( _lista_id_ == child )
        {
            _lista_id_ = null;
            return;
        }
        if ( _ponto_virgula_ == child )
        {
            _ponto_virgula_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _variavel_ == oldChild )
        {
            setVariavel ((TVariavel) newChild);
            return;
        }
        if ( _tipo_ == oldChild )
        {
            setTipo ((PTipo) newChild);
            return;
        }
        if ( _lista_id_ == oldChild )
        {
            setListaId ((PListaId) newChild);
            return;
        }
        if ( _ponto_virgula_ == oldChild )
        {
            setPontoVirgula ((TPontoVirgula) newChild);
            return;
        }
    }

}
