/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class ADifExp extends PExp
{
    private TNegacao _negacao_;
    private PExp _exp_;

    public ADifExp ()
    {
    }

    public ADifExp (
            TNegacao _negacao_,
            PExp _exp_
    )
    {
        setNegacao (_negacao_);
        setExp (_exp_);
    }

    public Object clone()
    {
        return new ADifExp (
            (TNegacao)cloneNode (_negacao_),
            (PExp)cloneNode (_exp_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADifExp(this);
    }

    public TNegacao getNegacao ()
    {
        return _negacao_;
    }

    public void setNegacao (TNegacao node)
    {
        if(_negacao_ != null)
        {
            _negacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _negacao_ = node;
    }
    public PExp getExp ()
    {
        return _exp_;
    }

    public void setExp (PExp node)
    {
        if(_exp_ != null)
        {
            _exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exp_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_negacao_)
            + toString (_exp_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _negacao_ == child )
        {
            _negacao_ = null;
            return;
        }
        if ( _exp_ == child )
        {
            _exp_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _negacao_ == oldChild )
        {
            setNegacao ((TNegacao) newChild);
            return;
        }
        if ( _exp_ == oldChild )
        {
            setExp ((PExp) newChild);
            return;
        }
    }

}
