/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class AFamiliaFamilia extends PFamilia
{
    private PListaRelacao _lista_relacao_;
    private TPontoVirgula _ponto_virgula_;

    public AFamiliaFamilia ()
    {
    }

    public AFamiliaFamilia (
            PListaRelacao _lista_relacao_,
            TPontoVirgula _ponto_virgula_
    )
    {
        setListaRelacao (_lista_relacao_);
        setPontoVirgula (_ponto_virgula_);
    }

    public Object clone()
    {
        return new AFamiliaFamilia (
            (PListaRelacao)cloneNode (_lista_relacao_),
            (TPontoVirgula)cloneNode (_ponto_virgula_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFamiliaFamilia(this);
    }

    public PListaRelacao getListaRelacao ()
    {
        return _lista_relacao_;
    }

    public void setListaRelacao (PListaRelacao node)
    {
        if(_lista_relacao_ != null)
        {
            _lista_relacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lista_relacao_ = node;
    }
    public TPontoVirgula getPontoVirgula ()
    {
        return _ponto_virgula_;
    }

    public void setPontoVirgula (TPontoVirgula node)
    {
        if(_ponto_virgula_ != null)
        {
            _ponto_virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _ponto_virgula_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_lista_relacao_)
            + toString (_ponto_virgula_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _lista_relacao_ == child )
        {
            _lista_relacao_ = null;
            return;
        }
        if ( _ponto_virgula_ == child )
        {
            _ponto_virgula_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _lista_relacao_ == oldChild )
        {
            setListaRelacao ((PListaRelacao) newChild);
            return;
        }
        if ( _ponto_virgula_ == oldChild )
        {
            setPontoVirgula ((TPontoVirgula) newChild);
            return;
        }
    }

}
