/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class AFilhaRelacaoFilhaRelacao extends PFilhaRelacao
{
    private TFilhaDaClasse _filha_da_classe_;
    private TCid _cid_;

    public AFilhaRelacaoFilhaRelacao ()
    {
    }

    public AFilhaRelacaoFilhaRelacao (
            TFilhaDaClasse _filha_da_classe_,
            TCid _cid_
    )
    {
        setFilhaDaClasse (_filha_da_classe_);
        setCid (_cid_);
    }

    public Object clone()
    {
        return new AFilhaRelacaoFilhaRelacao (
            (TFilhaDaClasse)cloneNode (_filha_da_classe_),
            (TCid)cloneNode (_cid_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFilhaRelacaoFilhaRelacao(this);
    }

    public TFilhaDaClasse getFilhaDaClasse ()
    {
        return _filha_da_classe_;
    }

    public void setFilhaDaClasse (TFilhaDaClasse node)
    {
        if(_filha_da_classe_ != null)
        {
            _filha_da_classe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _filha_da_classe_ = node;
    }
    public TCid getCid ()
    {
        return _cid_;
    }

    public void setCid (TCid node)
    {
        if(_cid_ != null)
        {
            _cid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _cid_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_filha_da_classe_)
            + toString (_cid_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _filha_da_classe_ == child )
        {
            _filha_da_classe_ = null;
            return;
        }
        if ( _cid_ == child )
        {
            _cid_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _filha_da_classe_ == oldChild )
        {
            setFilhaDaClasse ((TFilhaDaClasse) newChild);
            return;
        }
        if ( _cid_ == oldChild )
        {
            setCid ((TCid) newChild);
            return;
        }
    }

}
