/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class AIgualExp extends PExp
{
    private PTermo _termo_;
    private TIgualdade _igualdade_;
    private PExp _exp_;

    public AIgualExp ()
    {
    }

    public AIgualExp (
            PTermo _termo_,
            TIgualdade _igualdade_,
            PExp _exp_
    )
    {
        setTermo (_termo_);
        setIgualdade (_igualdade_);
        setExp (_exp_);
    }

    public Object clone()
    {
        return new AIgualExp (
            (PTermo)cloneNode (_termo_),
            (TIgualdade)cloneNode (_igualdade_),
            (PExp)cloneNode (_exp_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIgualExp(this);
    }

    public PTermo getTermo ()
    {
        return _termo_;
    }

    public void setTermo (PTermo node)
    {
        if(_termo_ != null)
        {
            _termo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _termo_ = node;
    }
    public TIgualdade getIgualdade ()
    {
        return _igualdade_;
    }

    public void setIgualdade (TIgualdade node)
    {
        if(_igualdade_ != null)
        {
            _igualdade_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _igualdade_ = node;
    }
    public PExp getExp ()
    {
        return _exp_;
    }

    public void setExp (PExp node)
    {
        if(_exp_ != null)
        {
            _exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exp_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_termo_)
            + toString (_igualdade_)
            + toString (_exp_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _termo_ == child )
        {
            _termo_ = null;
            return;
        }
        if ( _igualdade_ == child )
        {
            _igualdade_ = null;
            return;
        }
        if ( _exp_ == child )
        {
            _exp_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _termo_ == oldChild )
        {
            setTermo ((PTermo) newChild);
            return;
        }
        if ( _igualdade_ == oldChild )
        {
            setIgualdade ((TIgualdade) newChild);
            return;
        }
        if ( _exp_ == oldChild )
        {
            setExp ((PExp) newChild);
            return;
        }
    }

}
