/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class AInteiroTermo extends PTermo
{
    private TNumeroInteiro _numero_inteiro_;

    public AInteiroTermo ()
    {
    }

    public AInteiroTermo (
            TNumeroInteiro _numero_inteiro_
    )
    {
        setNumeroInteiro (_numero_inteiro_);
    }

    public Object clone()
    {
        return new AInteiroTermo (
            (TNumeroInteiro)cloneNode (_numero_inteiro_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInteiroTermo(this);
    }

    public TNumeroInteiro getNumeroInteiro ()
    {
        return _numero_inteiro_;
    }

    public void setNumeroInteiro (TNumeroInteiro node)
    {
        if(_numero_inteiro_ != null)
        {
            _numero_inteiro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _numero_inteiro_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_numero_inteiro_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _numero_inteiro_ == child )
        {
            _numero_inteiro_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _numero_inteiro_ == oldChild )
        {
            setNumeroInteiro ((TNumeroInteiro) newChild);
            return;
        }
    }

}
