/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AListaDecConsListaDecCons extends PListaDecCons
{
    private PDecCons _decCons_;
    private PListaDecCons _listaDecCons_;

    public AListaDecConsListaDecCons()
    {
        // Constructor
    }

    public AListaDecConsListaDecCons(
        @SuppressWarnings("hiding") PDecCons _decCons_,
        @SuppressWarnings("hiding") PListaDecCons _listaDecCons_)
    {
        // Constructor
        setDecCons(_decCons_);

        setListaDecCons(_listaDecCons_);

    }

    @Override
    public Object clone()
    {
        return new AListaDecConsListaDecCons(
            cloneNode(this._decCons_),
            cloneNode(this._listaDecCons_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaDecConsListaDecCons(this);
    }

    public PDecCons getDecCons()
    {
        return this._decCons_;
    }

    public void setDecCons(PDecCons node)
    {
        if(this._decCons_ != null)
        {
            this._decCons_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decCons_ = node;
    }

    public PListaDecCons getListaDecCons()
    {
        return this._listaDecCons_;
    }

    public void setListaDecCons(PListaDecCons node)
    {
        if(this._listaDecCons_ != null)
        {
            this._listaDecCons_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaDecCons_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decCons_)
            + toString(this._listaDecCons_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decCons_ == child)
        {
            this._decCons_ = null;
            return;
        }

        if(this._listaDecCons_ == child)
        {
            this._listaDecCons_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decCons_ == oldChild)
        {
            setDecCons((PDecCons) newChild);
            return;
        }

        if(this._listaDecCons_ == oldChild)
        {
            setListaDecCons((PListaDecCons) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
