/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AListaRelacaoListaRelacao extends PListaRelacao
{
    private PRelacao _relacao_;
    private TEComercial _eComercial_;
    private PListaRelacao _listaRelacao_;

    public AListaRelacaoListaRelacao()
    {
        // Constructor
    }

    public AListaRelacaoListaRelacao(
        @SuppressWarnings("hiding") PRelacao _relacao_,
        @SuppressWarnings("hiding") TEComercial _eComercial_,
        @SuppressWarnings("hiding") PListaRelacao _listaRelacao_)
    {
        // Constructor
        setRelacao(_relacao_);

        setEComercial(_eComercial_);

        setListaRelacao(_listaRelacao_);

    }

    @Override
    public Object clone()
    {
        return new AListaRelacaoListaRelacao(
            cloneNode(this._relacao_),
            cloneNode(this._eComercial_),
            cloneNode(this._listaRelacao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaRelacaoListaRelacao(this);
    }

    public PRelacao getRelacao()
    {
        return this._relacao_;
    }

    public void setRelacao(PRelacao node)
    {
        if(this._relacao_ != null)
        {
            this._relacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relacao_ = node;
    }

    public TEComercial getEComercial()
    {
        return this._eComercial_;
    }

    public void setEComercial(TEComercial node)
    {
        if(this._eComercial_ != null)
        {
            this._eComercial_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eComercial_ = node;
    }

    public PListaRelacao getListaRelacao()
    {
        return this._listaRelacao_;
    }

    public void setListaRelacao(PListaRelacao node)
    {
        if(this._listaRelacao_ != null)
        {
            this._listaRelacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaRelacao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._relacao_)
            + toString(this._eComercial_)
            + toString(this._listaRelacao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._relacao_ == child)
        {
            this._relacao_ = null;
            return;
        }

        if(this._eComercial_ == child)
        {
            this._eComercial_ = null;
            return;
        }

        if(this._listaRelacao_ == child)
        {
            this._listaRelacao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._relacao_ == oldChild)
        {
            setRelacao((PRelacao) newChild);
            return;
        }

        if(this._eComercial_ == oldChild)
        {
            setEComercial((TEComercial) newChild);
            return;
        }

        if(this._listaRelacao_ == oldChild)
        {
            setListaRelacao((PListaRelacao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
