/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AListaClasseListaClasse extends PListaClasse
{
    private PDefClasse _defClasse_;
    private PListaClasse _listaClasse_;

    public AListaClasseListaClasse()
    {
        // Constructor
    }

    public AListaClasseListaClasse(
        @SuppressWarnings("hiding") PDefClasse _defClasse_,
        @SuppressWarnings("hiding") PListaClasse _listaClasse_)
    {
        // Constructor
        setDefClasse(_defClasse_);

        setListaClasse(_listaClasse_);

    }

    @Override
    public Object clone()
    {
        return new AListaClasseListaClasse(
            cloneNode(this._defClasse_),
            cloneNode(this._listaClasse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaClasseListaClasse(this);
    }

    public PDefClasse getDefClasse()
    {
        return this._defClasse_;
    }

    public void setDefClasse(PDefClasse node)
    {
        if(this._defClasse_ != null)
        {
            this._defClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._defClasse_ = node;
    }

    public PListaClasse getListaClasse()
    {
        return this._listaClasse_;
    }

    public void setListaClasse(PListaClasse node)
    {
        if(this._listaClasse_ != null)
        {
            this._listaClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaClasse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._defClasse_)
            + toString(this._listaClasse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._defClasse_ == child)
        {
            this._defClasse_ = null;
            return;
        }

        if(this._listaClasse_ == child)
        {
            this._listaClasse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._defClasse_ == oldChild)
        {
            setDefClasse((PDefClasse) newChild);
            return;
        }

        if(this._listaClasse_ == oldChild)
        {
            setListaClasse((PListaClasse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
