/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AListaComandosListaComandos extends PListaComandos
{
    private PComando _comando_;
    private PListaComandos _listaComandos_;

    public AListaComandosListaComandos()
    {
        // Constructor
    }

    public AListaComandosListaComandos(
        @SuppressWarnings("hiding") PComando _comando_,
        @SuppressWarnings("hiding") PListaComandos _listaComandos_)
    {
        // Constructor
        setComando(_comando_);

        setListaComandos(_listaComandos_);

    }

    @Override
    public Object clone()
    {
        return new AListaComandosListaComandos(
            cloneNode(this._comando_),
            cloneNode(this._listaComandos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaComandosListaComandos(this);
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    public PListaComandos getListaComandos()
    {
        return this._listaComandos_;
    }

    public void setListaComandos(PListaComandos node)
    {
        if(this._listaComandos_ != null)
        {
            this._listaComandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaComandos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comando_)
            + toString(this._listaComandos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        if(this._listaComandos_ == child)
        {
            this._listaComandos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        if(this._listaComandos_ == oldChild)
        {
            setListaComandos((PListaComandos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
