/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class AListaClasseListaClasse extends PListaClasse
{
    private PDefClasse _def_classe_;
    private PListaClasse _lista_classe_;

    public AListaClasseListaClasse ()
    {
    }

    public AListaClasseListaClasse (
            PDefClasse _def_classe_,
            PListaClasse _lista_classe_
    )
    {
        setDefClasse (_def_classe_);
        setListaClasse (_lista_classe_);
    }

    public Object clone()
    {
        return new AListaClasseListaClasse (
            (PDefClasse)cloneNode (_def_classe_),
            (PListaClasse)cloneNode (_lista_classe_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaClasseListaClasse(this);
    }

    public PDefClasse getDefClasse ()
    {
        return _def_classe_;
    }

    public void setDefClasse (PDefClasse node)
    {
        if(_def_classe_ != null)
        {
            _def_classe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _def_classe_ = node;
    }
    public PListaClasse getListaClasse ()
    {
        return _lista_classe_;
    }

    public void setListaClasse (PListaClasse node)
    {
        if(_lista_classe_ != null)
        {
            _lista_classe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lista_classe_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_def_classe_)
            + toString (_lista_classe_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _def_classe_ == child )
        {
            _def_classe_ = null;
            return;
        }
        if ( _lista_classe_ == child )
        {
            _lista_classe_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _def_classe_ == oldChild )
        {
            setDefClasse ((PDefClasse) newChild);
            return;
        }
        if ( _lista_classe_ == oldChild )
        {
            setListaClasse ((PListaClasse) newChild);
            return;
        }
    }

}
