/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AListaInicializacaoListaInicializacao extends PListaInicializacao
{
    private PInicializacao _inicializacao_;
    private TVirgula _virgula_;
    private PListaInicializacao _listaInicializacao_;

    public AListaInicializacaoListaInicializacao()
    {
        // Constructor
    }

    public AListaInicializacaoListaInicializacao(
        @SuppressWarnings("hiding") PInicializacao _inicializacao_,
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PListaInicializacao _listaInicializacao_)
    {
        // Constructor
        setInicializacao(_inicializacao_);

        setVirgula(_virgula_);

        setListaInicializacao(_listaInicializacao_);

    }

    @Override
    public Object clone()
    {
        return new AListaInicializacaoListaInicializacao(
            cloneNode(this._inicializacao_),
            cloneNode(this._virgula_),
            cloneNode(this._listaInicializacao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaInicializacaoListaInicializacao(this);
    }

    public PInicializacao getInicializacao()
    {
        return this._inicializacao_;
    }

    public void setInicializacao(PInicializacao node)
    {
        if(this._inicializacao_ != null)
        {
            this._inicializacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inicializacao_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PListaInicializacao getListaInicializacao()
    {
        return this._listaInicializacao_;
    }

    public void setListaInicializacao(PListaInicializacao node)
    {
        if(this._listaInicializacao_ != null)
        {
            this._listaInicializacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaInicializacao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inicializacao_)
            + toString(this._virgula_)
            + toString(this._listaInicializacao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inicializacao_ == child)
        {
            this._inicializacao_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._listaInicializacao_ == child)
        {
            this._listaInicializacao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inicializacao_ == oldChild)
        {
            setInicializacao((PInicializacao) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._listaInicializacao_ == oldChild)
        {
            setListaInicializacao((PListaInicializacao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
