/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class AListaExpListaExp extends PListaExp
{
    private PExp _exp_;
    private TVirgula _virgula_;
    private PListaExp _lista_exp_;

    public AListaExpListaExp ()
    {
    }

    public AListaExpListaExp (
            PExp _exp_,
            TVirgula _virgula_,
            PListaExp _lista_exp_
    )
    {
        setExp (_exp_);
        setVirgula (_virgula_);
        setListaExp (_lista_exp_);
    }

    public Object clone()
    {
        return new AListaExpListaExp (
            (PExp)cloneNode (_exp_),
            (TVirgula)cloneNode (_virgula_),
            (PListaExp)cloneNode (_lista_exp_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaExpListaExp(this);
    }

    public PExp getExp ()
    {
        return _exp_;
    }

    public void setExp (PExp node)
    {
        if(_exp_ != null)
        {
            _exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exp_ = node;
    }
    public TVirgula getVirgula ()
    {
        return _virgula_;
    }

    public void setVirgula (TVirgula node)
    {
        if(_virgula_ != null)
        {
            _virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _virgula_ = node;
    }
    public PListaExp getListaExp ()
    {
        return _lista_exp_;
    }

    public void setListaExp (PListaExp node)
    {
        if(_lista_exp_ != null)
        {
            _lista_exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lista_exp_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_exp_)
            + toString (_virgula_)
            + toString (_lista_exp_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _exp_ == child )
        {
            _exp_ = null;
            return;
        }
        if ( _virgula_ == child )
        {
            _virgula_ = null;
            return;
        }
        if ( _lista_exp_ == child )
        {
            _lista_exp_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _exp_ == oldChild )
        {
            setExp ((PExp) newChild);
            return;
        }
        if ( _virgula_ == oldChild )
        {
            setVirgula ((TVirgula) newChild);
            return;
        }
        if ( _lista_exp_ == oldChild )
        {
            setListaExp ((PListaExp) newChild);
            return;
        }
    }

}
