/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AListaParametroListaParametro extends PListaParametro
{
    private PParametro _parametro_;
    private TVirgula _virgula_;
    private PListaParametro _listaParametro_;

    public AListaParametroListaParametro()
    {
        // Constructor
    }

    public AListaParametroListaParametro(
        @SuppressWarnings("hiding") PParametro _parametro_,
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PListaParametro _listaParametro_)
    {
        // Constructor
        setParametro(_parametro_);

        setVirgula(_virgula_);

        setListaParametro(_listaParametro_);

    }

    @Override
    public Object clone()
    {
        return new AListaParametroListaParametro(
            cloneNode(this._parametro_),
            cloneNode(this._virgula_),
            cloneNode(this._listaParametro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaParametroListaParametro(this);
    }

    public PParametro getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(PParametro node)
    {
        if(this._parametro_ != null)
        {
            this._parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametro_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PListaParametro getListaParametro()
    {
        return this._listaParametro_;
    }

    public void setListaParametro(PListaParametro node)
    {
        if(this._listaParametro_ != null)
        {
            this._listaParametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaParametro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parametro_)
            + toString(this._virgula_)
            + toString(this._listaParametro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parametro_ == child)
        {
            this._parametro_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._listaParametro_ == child)
        {
            this._listaParametro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parametro_ == oldChild)
        {
            setParametro((PParametro) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._listaParametro_ == oldChild)
        {
            setListaParametro((PListaParametro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
