/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class AListaDecConsListaDecCons extends PListaDecCons
{
    private PDecCons _dec_cons_;
    private PListaDecCons _lista_dec_cons_;

    public AListaDecConsListaDecCons ()
    {
    }

    public AListaDecConsListaDecCons (
            PDecCons _dec_cons_,
            PListaDecCons _lista_dec_cons_
    )
    {
        setDecCons (_dec_cons_);
        setListaDecCons (_lista_dec_cons_);
    }

    public Object clone()
    {
        return new AListaDecConsListaDecCons (
            (PDecCons)cloneNode (_dec_cons_),
            (PListaDecCons)cloneNode (_lista_dec_cons_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaDecConsListaDecCons(this);
    }

    public PDecCons getDecCons ()
    {
        return _dec_cons_;
    }

    public void setDecCons (PDecCons node)
    {
        if(_dec_cons_ != null)
        {
            _dec_cons_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dec_cons_ = node;
    }
    public PListaDecCons getListaDecCons ()
    {
        return _lista_dec_cons_;
    }

    public void setListaDecCons (PListaDecCons node)
    {
        if(_lista_dec_cons_ != null)
        {
            _lista_dec_cons_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lista_dec_cons_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_dec_cons_)
            + toString (_lista_dec_cons_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _dec_cons_ == child )
        {
            _dec_cons_ = null;
            return;
        }
        if ( _lista_dec_cons_ == child )
        {
            _lista_dec_cons_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _dec_cons_ == oldChild )
        {
            setDecCons ((PDecCons) newChild);
            return;
        }
        if ( _lista_dec_cons_ == oldChild )
        {
            setListaDecCons ((PListaDecCons) newChild);
            return;
        }
    }

}
