/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class AMenorCondExp2 extends PCondExp2
{
    private PTermo _termo_;
    private TMenorQue _menor_que_;
    private PCondExp2 _cond_exp2_;

    public AMenorCondExp2 ()
    {
    }

    public AMenorCondExp2 (
            PTermo _termo_,
            TMenorQue _menor_que_,
            PCondExp2 _cond_exp2_
    )
    {
        setTermo (_termo_);
        setMenorQue (_menor_que_);
        setCondExp2 (_cond_exp2_);
    }

    public Object clone()
    {
        return new AMenorCondExp2 (
            (PTermo)cloneNode (_termo_),
            (TMenorQue)cloneNode (_menor_que_),
            (PCondExp2)cloneNode (_cond_exp2_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenorCondExp2(this);
    }

    public PTermo getTermo ()
    {
        return _termo_;
    }

    public void setTermo (PTermo node)
    {
        if(_termo_ != null)
        {
            _termo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _termo_ = node;
    }
    public TMenorQue getMenorQue ()
    {
        return _menor_que_;
    }

    public void setMenorQue (TMenorQue node)
    {
        if(_menor_que_ != null)
        {
            _menor_que_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _menor_que_ = node;
    }
    public PCondExp2 getCondExp2 ()
    {
        return _cond_exp2_;
    }

    public void setCondExp2 (PCondExp2 node)
    {
        if(_cond_exp2_ != null)
        {
            _cond_exp2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _cond_exp2_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_termo_)
            + toString (_menor_que_)
            + toString (_cond_exp2_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _termo_ == child )
        {
            _termo_ = null;
            return;
        }
        if ( _menor_que_ == child )
        {
            _menor_que_ = null;
            return;
        }
        if ( _cond_exp2_ == child )
        {
            _cond_exp2_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _termo_ == oldChild )
        {
            setTermo ((PTermo) newChild);
            return;
        }
        if ( _menor_que_ == oldChild )
        {
            setMenorQue ((TMenorQue) newChild);
            return;
        }
        if ( _cond_exp2_ == oldChild )
        {
            setCondExp2 ((PCondExp2) newChild);
            return;
        }
    }

}
