/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class AMenorExp extends PExp
{
    private PTermo _termo_;
    private TMenorQue _menor_que_;
    private PExp _exp_;

    public AMenorExp ()
    {
    }

    public AMenorExp (
            PTermo _termo_,
            TMenorQue _menor_que_,
            PExp _exp_
    )
    {
        setTermo (_termo_);
        setMenorQue (_menor_que_);
        setExp (_exp_);
    }

    public Object clone()
    {
        return new AMenorExp (
            (PTermo)cloneNode (_termo_),
            (TMenorQue)cloneNode (_menor_que_),
            (PExp)cloneNode (_exp_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenorExp(this);
    }

    public PTermo getTermo ()
    {
        return _termo_;
    }

    public void setTermo (PTermo node)
    {
        if(_termo_ != null)
        {
            _termo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _termo_ = node;
    }
    public TMenorQue getMenorQue ()
    {
        return _menor_que_;
    }

    public void setMenorQue (TMenorQue node)
    {
        if(_menor_que_ != null)
        {
            _menor_que_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _menor_que_ = node;
    }
    public PExp getExp ()
    {
        return _exp_;
    }

    public void setExp (PExp node)
    {
        if(_exp_ != null)
        {
            _exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exp_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_termo_)
            + toString (_menor_que_)
            + toString (_exp_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _termo_ == child )
        {
            _termo_ = null;
            return;
        }
        if ( _menor_que_ == child )
        {
            _menor_que_ = null;
            return;
        }
        if ( _exp_ == child )
        {
            _exp_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _termo_ == oldChild )
        {
            setTermo ((PTermo) newChild);
            return;
        }
        if ( _menor_que_ == oldChild )
        {
            setMenorQue ((TMenorQue) newChild);
            return;
        }
        if ( _exp_ == oldChild )
        {
            setExp ((PExp) newChild);
            return;
        }
    }

}
