/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class AModCondExp2 extends PCondExp2
{
    private PTermo _termo_;
    private TModulo _modulo_;
    private PCondExp2 _cond_exp2_;

    public AModCondExp2 ()
    {
    }

    public AModCondExp2 (
            PTermo _termo_,
            TModulo _modulo_,
            PCondExp2 _cond_exp2_
    )
    {
        setTermo (_termo_);
        setModulo (_modulo_);
        setCondExp2 (_cond_exp2_);
    }

    public Object clone()
    {
        return new AModCondExp2 (
            (PTermo)cloneNode (_termo_),
            (TModulo)cloneNode (_modulo_),
            (PCondExp2)cloneNode (_cond_exp2_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModCondExp2(this);
    }

    public PTermo getTermo ()
    {
        return _termo_;
    }

    public void setTermo (PTermo node)
    {
        if(_termo_ != null)
        {
            _termo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _termo_ = node;
    }
    public TModulo getModulo ()
    {
        return _modulo_;
    }

    public void setModulo (TModulo node)
    {
        if(_modulo_ != null)
        {
            _modulo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _modulo_ = node;
    }
    public PCondExp2 getCondExp2 ()
    {
        return _cond_exp2_;
    }

    public void setCondExp2 (PCondExp2 node)
    {
        if(_cond_exp2_ != null)
        {
            _cond_exp2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _cond_exp2_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_termo_)
            + toString (_modulo_)
            + toString (_cond_exp2_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _termo_ == child )
        {
            _termo_ = null;
            return;
        }
        if ( _modulo_ == child )
        {
            _modulo_ = null;
            return;
        }
        if ( _cond_exp2_ == child )
        {
            _cond_exp2_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _termo_ == oldChild )
        {
            setTermo ((PTermo) newChild);
            return;
        }
        if ( _modulo_ == oldChild )
        {
            setModulo ((TModulo) newChild);
            return;
        }
        if ( _cond_exp2_ == oldChild )
        {
            setCondExp2 ((PCondExp2) newChild);
            return;
        }
    }

}
