/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class AMultiExp extends PExp
{
    private PTermo _termo_;
    private TMultiplicacao _multiplicacao_;
    private PExp _exp_;

    public AMultiExp ()
    {
    }

    public AMultiExp (
            PTermo _termo_,
            TMultiplicacao _multiplicacao_,
            PExp _exp_
    )
    {
        setTermo (_termo_);
        setMultiplicacao (_multiplicacao_);
        setExp (_exp_);
    }

    public Object clone()
    {
        return new AMultiExp (
            (PTermo)cloneNode (_termo_),
            (TMultiplicacao)cloneNode (_multiplicacao_),
            (PExp)cloneNode (_exp_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiExp(this);
    }

    public PTermo getTermo ()
    {
        return _termo_;
    }

    public void setTermo (PTermo node)
    {
        if(_termo_ != null)
        {
            _termo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _termo_ = node;
    }
    public TMultiplicacao getMultiplicacao ()
    {
        return _multiplicacao_;
    }

    public void setMultiplicacao (TMultiplicacao node)
    {
        if(_multiplicacao_ != null)
        {
            _multiplicacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _multiplicacao_ = node;
    }
    public PExp getExp ()
    {
        return _exp_;
    }

    public void setExp (PExp node)
    {
        if(_exp_ != null)
        {
            _exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exp_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_termo_)
            + toString (_multiplicacao_)
            + toString (_exp_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _termo_ == child )
        {
            _termo_ = null;
            return;
        }
        if ( _multiplicacao_ == child )
        {
            _multiplicacao_ = null;
            return;
        }
        if ( _exp_ == child )
        {
            _exp_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _termo_ == oldChild )
        {
            setTermo ((PTermo) newChild);
            return;
        }
        if ( _multiplicacao_ == oldChild )
        {
            setMultiplicacao ((TMultiplicacao) newChild);
            return;
        }
        if ( _exp_ == oldChild )
        {
            setExp ((PExp) newChild);
            return;
        }
    }

}
