/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class AObjDec extends PDec
{
    private PDecObj _dec_obj_;

    public AObjDec ()
    {
    }

    public AObjDec (
            PDecObj _dec_obj_
    )
    {
        setDecObj (_dec_obj_);
    }

    public Object clone()
    {
        return new AObjDec (
            (PDecObj)cloneNode (_dec_obj_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAObjDec(this);
    }

    public PDecObj getDecObj ()
    {
        return _dec_obj_;
    }

    public void setDecObj (PDecObj node)
    {
        if(_dec_obj_ != null)
        {
            _dec_obj_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dec_obj_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_dec_obj_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _dec_obj_ == child )
        {
            _dec_obj_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _dec_obj_ == oldChild )
        {
            setDecObj ((PDecObj) newChild);
            return;
        }
    }

}
