/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class AOrExp extends PExp
{
    private PTermo _termo_;
    private TOu _ou_;
    private PExp _exp_;

    public AOrExp ()
    {
    }

    public AOrExp (
            PTermo _termo_,
            TOu _ou_,
            PExp _exp_
    )
    {
        setTermo (_termo_);
        setOu (_ou_);
        setExp (_exp_);
    }

    public Object clone()
    {
        return new AOrExp (
            (PTermo)cloneNode (_termo_),
            (TOu)cloneNode (_ou_),
            (PExp)cloneNode (_exp_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrExp(this);
    }

    public PTermo getTermo ()
    {
        return _termo_;
    }

    public void setTermo (PTermo node)
    {
        if(_termo_ != null)
        {
            _termo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _termo_ = node;
    }
    public TOu getOu ()
    {
        return _ou_;
    }

    public void setOu (TOu node)
    {
        if(_ou_ != null)
        {
            _ou_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _ou_ = node;
    }
    public PExp getExp ()
    {
        return _exp_;
    }

    public void setExp (PExp node)
    {
        if(_exp_ != null)
        {
            _exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exp_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_termo_)
            + toString (_ou_)
            + toString (_exp_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _termo_ == child )
        {
            _termo_ = null;
            return;
        }
        if ( _ou_ == child )
        {
            _ou_ = null;
            return;
        }
        if ( _exp_ == child )
        {
            _exp_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _termo_ == oldChild )
        {
            setTermo ((PTermo) newChild);
            return;
        }
        if ( _ou_ == oldChild )
        {
            setOu ((TOu) newChild);
            return;
        }
        if ( _exp_ == oldChild )
        {
            setExp ((PExp) newChild);
            return;
        }
    }

}
