/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AParametrosParametros extends PParametros
{
    private PListaParametro _listaParametro_;

    public AParametrosParametros()
    {
        // Constructor
    }

    public AParametrosParametros(
        @SuppressWarnings("hiding") PListaParametro _listaParametro_)
    {
        // Constructor
        setListaParametro(_listaParametro_);

    }

    @Override
    public Object clone()
    {
        return new AParametrosParametros(
            cloneNode(this._listaParametro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametrosParametros(this);
    }

    public PListaParametro getListaParametro()
    {
        return this._listaParametro_;
    }

    public void setListaParametro(PListaParametro node)
    {
        if(this._listaParametro_ != null)
        {
            this._listaParametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaParametro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaParametro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaParametro_ == child)
        {
            this._listaParametro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaParametro_ == oldChild)
        {
            setListaParametro((PListaParametro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
