/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class AParTermo extends PTermo
{
    private TParentesesEsquerdo _parenteses_esquerdo_;
    private PExp _exp_;
    private TParentesesDireito _parenteses_direito_;

    public AParTermo ()
    {
    }

    public AParTermo (
            TParentesesEsquerdo _parenteses_esquerdo_,
            PExp _exp_,
            TParentesesDireito _parenteses_direito_
    )
    {
        setParentesesEsquerdo (_parenteses_esquerdo_);
        setExp (_exp_);
        setParentesesDireito (_parenteses_direito_);
    }

    public Object clone()
    {
        return new AParTermo (
            (TParentesesEsquerdo)cloneNode (_parenteses_esquerdo_),
            (PExp)cloneNode (_exp_),
            (TParentesesDireito)cloneNode (_parenteses_direito_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParTermo(this);
    }

    public TParentesesEsquerdo getParentesesEsquerdo ()
    {
        return _parenteses_esquerdo_;
    }

    public void setParentesesEsquerdo (TParentesesEsquerdo node)
    {
        if(_parenteses_esquerdo_ != null)
        {
            _parenteses_esquerdo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _parenteses_esquerdo_ = node;
    }
    public PExp getExp ()
    {
        return _exp_;
    }

    public void setExp (PExp node)
    {
        if(_exp_ != null)
        {
            _exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exp_ = node;
    }
    public TParentesesDireito getParentesesDireito ()
    {
        return _parenteses_direito_;
    }

    public void setParentesesDireito (TParentesesDireito node)
    {
        if(_parenteses_direito_ != null)
        {
            _parenteses_direito_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _parenteses_direito_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_parenteses_esquerdo_)
            + toString (_exp_)
            + toString (_parenteses_direito_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _parenteses_esquerdo_ == child )
        {
            _parenteses_esquerdo_ = null;
            return;
        }
        if ( _exp_ == child )
        {
            _exp_ = null;
            return;
        }
        if ( _parenteses_direito_ == child )
        {
            _parenteses_direito_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _parenteses_esquerdo_ == oldChild )
        {
            setParentesesEsquerdo ((TParentesesEsquerdo) newChild);
            return;
        }
        if ( _exp_ == oldChild )
        {
            setExp ((PExp) newChild);
            return;
        }
        if ( _parenteses_direito_ == oldChild )
        {
            setParentesesDireito ((TParentesesDireito) newChild);
            return;
        }
    }

}
