/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class AParametroListaParametro extends PListaParametro
{
    private PParametro _parametro_;

    public AParametroListaParametro ()
    {
    }

    public AParametroListaParametro (
            PParametro _parametro_
    )
    {
        setParametro (_parametro_);
    }

    public Object clone()
    {
        return new AParametroListaParametro (
            (PParametro)cloneNode (_parametro_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametroListaParametro(this);
    }

    public PParametro getParametro ()
    {
        return _parametro_;
    }

    public void setParametro (PParametro node)
    {
        if(_parametro_ != null)
        {
            _parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _parametro_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_parametro_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _parametro_ == child )
        {
            _parametro_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _parametro_ == oldChild )
        {
            setParametro ((PParametro) newChild);
            return;
        }
    }

}
