/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class APrimitivoTipo extends PTipo
{
    private PTipoPrimitivo _tipo_primitivo_;

    public APrimitivoTipo ()
    {
    }

    public APrimitivoTipo (
            PTipoPrimitivo _tipo_primitivo_
    )
    {
        setTipoPrimitivo (_tipo_primitivo_);
    }

    public Object clone()
    {
        return new APrimitivoTipo (
            (PTipoPrimitivo)cloneNode (_tipo_primitivo_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrimitivoTipo(this);
    }

    public PTipoPrimitivo getTipoPrimitivo ()
    {
        return _tipo_primitivo_;
    }

    public void setTipoPrimitivo (PTipoPrimitivo node)
    {
        if(_tipo_primitivo_ != null)
        {
            _tipo_primitivo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tipo_primitivo_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_tipo_primitivo_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _tipo_primitivo_ == child )
        {
            _tipo_primitivo_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _tipo_primitivo_ == oldChild )
        {
            setTipoPrimitivo ((PTipoPrimitivo) newChild);
            return;
        }
    }

}
