/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AProgramaPrograma extends PPrograma
{
    private PFamilia _familia_;
    private PListaClasse _listaClasse_;

    public AProgramaPrograma()
    {
        // Constructor
    }

    public AProgramaPrograma(
        @SuppressWarnings("hiding") PFamilia _familia_,
        @SuppressWarnings("hiding") PListaClasse _listaClasse_)
    {
        // Constructor
        setFamilia(_familia_);

        setListaClasse(_listaClasse_);

    }

    @Override
    public Object clone()
    {
        return new AProgramaPrograma(
            cloneNode(this._familia_),
            cloneNode(this._listaClasse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgramaPrograma(this);
    }

    public PFamilia getFamilia()
    {
        return this._familia_;
    }

    public void setFamilia(PFamilia node)
    {
        if(this._familia_ != null)
        {
            this._familia_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._familia_ = node;
    }

    public PListaClasse getListaClasse()
    {
        return this._listaClasse_;
    }

    public void setListaClasse(PListaClasse node)
    {
        if(this._listaClasse_ != null)
        {
            this._listaClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaClasse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._familia_)
            + toString(this._listaClasse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._familia_ == child)
        {
            this._familia_ = null;
            return;
        }

        if(this._listaClasse_ == child)
        {
            this._listaClasse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._familia_ == oldChild)
        {
            setFamilia((PFamilia) newChild);
            return;
        }

        if(this._listaClasse_ == oldChild)
        {
            setListaClasse((PListaClasse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
