/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class ARelacaoListaRelacao extends PListaRelacao
{
    private PRelacao _relacao_;

    public ARelacaoListaRelacao()
    {
        // Constructor
    }

    public ARelacaoListaRelacao(
        @SuppressWarnings("hiding") PRelacao _relacao_)
    {
        // Constructor
        setRelacao(_relacao_);

    }

    @Override
    public Object clone()
    {
        return new ARelacaoListaRelacao(
            cloneNode(this._relacao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelacaoListaRelacao(this);
    }

    public PRelacao getRelacao()
    {
        return this._relacao_;
    }

    public void setRelacao(PRelacao node)
    {
        if(this._relacao_ != null)
        {
            this._relacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relacao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._relacao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._relacao_ == child)
        {
            this._relacao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._relacao_ == oldChild)
        {
            setRelacao((PRelacao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
