/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class AVazioParametros extends PParametros
{


    public AVazioParametros (
    )
    {
    }

    public Object clone()
    {
        return new AVazioParametros (
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVazioParametros(this);
    }


    public String toString()
    {
        return ""
        ;
    }

    void removeChild(Node child)
    {
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

}
