/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

public final class AVazioFamilia extends PFamilia
{


    public AVazioFamilia (
    )
    {
    }

    public Object clone()
    {
        return new AVazioFamilia (
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVazioFamilia(this);
    }


    public String toString()
    {
        return ""
        ;
    }

    void removeChild(Node child)
    {
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

}
