/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

public final class TAtribuicao extends Token
{
    public TAtribuicao()
    {
        super.setText("=");
    }

    public TAtribuicao(int line, int pos)
    {
        super.setText("=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TAtribuicao(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAtribuicao(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TAtribuicao text.");
    }
}
