/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

public final class TComeca extends Token
{
    public TComeca()
    {
        super.setText("come\u00e7a");
    }

    public TComeca(int line, int pos)
    {
        super.setText("come\u00e7a");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TComeca(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTComeca(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TComeca text.");
    }
}
