/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

public final class TConstante extends Token
{
    public TConstante()
    {
        super.setText("cons");
    }

    public TConstante(int line, int pos)
    {
        super.setText("cons");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TConstante(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTConstante(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TConstante text.");
    }
}
