/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

public final class TEnquanto extends Token
{
    public TEnquanto()
    {
        super.setText("enquanto");
    }

    public TEnquanto(int line, int pos)
    {
        super.setText("enquanto");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TEnquanto(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEnquanto(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TEnquanto text.");
    }
}
