/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

public final class TFilhaDaClasse extends Token
{
    public TFilhaDaClasse()
    {
        super.setText("filha da classe");
    }

    public TFilhaDaClasse(int line, int pos)
    {
        super.setText("filha da classe");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TFilhaDaClasse(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFilhaDaClasse(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TFilhaDaClasse text.");
    }
}
