/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

public final class TIgualdade extends Token
{
    public TIgualdade()
    {
        super.setText("==");
    }

    public TIgualdade(int line, int pos)
    {
        super.setText("==");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TIgualdade(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIgualdade(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TIgualdade text.");
    }
}
