/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

public final class TMenorQue extends Token
{
    public TMenorQue()
    {
        super.setText("<");
    }

    public TMenorQue(int line, int pos)
    {
        super.setText("<");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMenorQue(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMenorQue(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMenorQue text.");
    }
}
