/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

public final class TObjeto extends Token
{
    public TObjeto()
    {
        super.setText("objeto");
    }

    public TObjeto(int line, int pos)
    {
        super.setText("objeto");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TObjeto(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTObjeto(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TObjeto text.");
    }
}
