/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class TObjeto extends Token
{
    public TObjeto()
    {
        super.setText("objeto");
    }

    public TObjeto(int line, int pos)
    {
        super.setText("objeto");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TObjeto(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTObjeto(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TObjeto text.");
    }
}
