/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

public final class TParentesesEsquerdo extends Token
{
    public TParentesesEsquerdo()
    {
        super.setText("(");
    }

    public TParentesesEsquerdo(int line, int pos)
    {
        super.setText("(");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TParentesesEsquerdo(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTParentesesEsquerdo(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TParentesesEsquerdo text.");
    }
}
