/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

public final class TPonto extends Token
{
    public TPonto()
    {
        super.setText(".");
    }

    public TPonto(int line, int pos)
    {
        super.setText(".");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TPonto(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPonto(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TPonto text.");
    }
}
