/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

public final class TProcedimento extends Token
{
    public TProcedimento()
    {
        super.setText("procedimento");
    }

    public TProcedimento(int line, int pos)
    {
        super.setText("procedimento");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TProcedimento(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTProcedimento(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TProcedimento text.");
    }
}
