/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

public final class TSe extends Token
{
    public TSe()
    {
        super.setText("se");
    }

    public TSe(int line, int pos)
    {
        super.setText("se");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSe(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSe(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSe text.");
    }
}
