/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

public final class TTermina extends Token
{
    public TTermina()
    {
        super.setText("termina");
    }

    public TTermina(int line, int pos)
    {
        super.setText("termina");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TTermina(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTermina(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TTermina text.");
    }
}
