/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

public final class TVirgula extends Token
{
    public TVirgula()
    {
        super.setText(",");
    }

    public TVirgula(int line, int pos)
    {
        super.setText(",");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TVirgula(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVirgula(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TVirgula text.");
    }
}
