/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.analysis;

import java.util.*;
import quase.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPPrograma().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAProgramaPrograma(AProgramaPrograma node)
    {
        defaultIn(node);
    }

    public void outAProgramaPrograma(AProgramaPrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProgramaPrograma(AProgramaPrograma node)
    {
        inAProgramaPrograma(node);
        if(node.getFamilia() != null)
        {
            node.getFamilia().apply(this);
        }
        if(node.getListaClasse() != null)
        {
            node.getListaClasse().apply(this);
        }
        outAProgramaPrograma(node);
    }

    public void inAListaClasseListaClasse(AListaClasseListaClasse node)
    {
        defaultIn(node);
    }

    public void outAListaClasseListaClasse(AListaClasseListaClasse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaClasseListaClasse(AListaClasseListaClasse node)
    {
        inAListaClasseListaClasse(node);
        if(node.getDefClasse() != null)
        {
            node.getDefClasse().apply(this);
        }
        if(node.getListaClasse() != null)
        {
            node.getListaClasse().apply(this);
        }
        outAListaClasseListaClasse(node);
    }

    public void inAClasseListaClasse(AClasseListaClasse node)
    {
        defaultIn(node);
    }

    public void outAClasseListaClasse(AClasseListaClasse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAClasseListaClasse(AClasseListaClasse node)
    {
        inAClasseListaClasse(node);
        if(node.getDefClasse() != null)
        {
            node.getDefClasse().apply(this);
        }
        outAClasseListaClasse(node);
    }

    public void inAFamiliaFamilia(AFamiliaFamilia node)
    {
        defaultIn(node);
    }

    public void outAFamiliaFamilia(AFamiliaFamilia node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFamiliaFamilia(AFamiliaFamilia node)
    {
        inAFamiliaFamilia(node);
        if(node.getListaRelacao() != null)
        {
            node.getListaRelacao().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAFamiliaFamilia(node);
    }

    public void inAVazioFamilia(AVazioFamilia node)
    {
        defaultIn(node);
    }

    public void outAVazioFamilia(AVazioFamilia node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVazioFamilia(AVazioFamilia node)
    {
        inAVazioFamilia(node);
        outAVazioFamilia(node);
    }

    public void inAListaRelacaoListaRelacao(AListaRelacaoListaRelacao node)
    {
        defaultIn(node);
    }

    public void outAListaRelacaoListaRelacao(AListaRelacaoListaRelacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaRelacaoListaRelacao(AListaRelacaoListaRelacao node)
    {
        inAListaRelacaoListaRelacao(node);
        if(node.getRelacao() != null)
        {
            node.getRelacao().apply(this);
        }
        if(node.getEComercial() != null)
        {
            node.getEComercial().apply(this);
        }
        if(node.getListaRelacao() != null)
        {
            node.getListaRelacao().apply(this);
        }
        outAListaRelacaoListaRelacao(node);
    }

    public void inARelacaoListaRelacao(ARelacaoListaRelacao node)
    {
        defaultIn(node);
    }

    public void outARelacaoListaRelacao(ARelacaoListaRelacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARelacaoListaRelacao(ARelacaoListaRelacao node)
    {
        inARelacaoListaRelacao(node);
        if(node.getRelacao() != null)
        {
            node.getRelacao().apply(this);
        }
        outARelacaoListaRelacao(node);
    }

    public void inARelacaoRelacao(ARelacaoRelacao node)
    {
        defaultIn(node);
    }

    public void outARelacaoRelacao(ARelacaoRelacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARelacaoRelacao(ARelacaoRelacao node)
    {
        inARelacaoRelacao(node);
        if(node.getClasse() != null)
        {
            node.getClasse().apply(this);
        }
        if(node.getCid() != null)
        {
            node.getCid().apply(this);
        }
        if(node.getFilhaRelacao() != null)
        {
            node.getFilhaRelacao().apply(this);
        }
        outARelacaoRelacao(node);
    }

    public void inAFilhaRelacaoFilhaRelacao(AFilhaRelacaoFilhaRelacao node)
    {
        defaultIn(node);
    }

    public void outAFilhaRelacaoFilhaRelacao(AFilhaRelacaoFilhaRelacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFilhaRelacaoFilhaRelacao(AFilhaRelacaoFilhaRelacao node)
    {
        inAFilhaRelacaoFilhaRelacao(node);
        if(node.getFilhaDaClasse() != null)
        {
            node.getFilhaDaClasse().apply(this);
        }
        if(node.getCid() != null)
        {
            node.getCid().apply(this);
        }
        outAFilhaRelacaoFilhaRelacao(node);
    }

    public void inADefClasseDefClasse(ADefClasseDefClasse node)
    {
        defaultIn(node);
    }

    public void outADefClasseDefClasse(ADefClasseDefClasse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefClasseDefClasse(ADefClasseDefClasse node)
    {
        inADefClasseDefClasse(node);
        if(node.getClasse() != null)
        {
            node.getClasse().apply(this);
        }
        if(node.getCid() != null)
        {
            node.getCid().apply(this);
        }
        if(node.getComeca() != null)
        {
            node.getComeca().apply(this);
        }
        if(node.getAtributos() != null)
        {
            node.getAtributos().apply(this);
        }
        if(node.getMetodos() != null)
        {
            node.getMetodos().apply(this);
        }
        if(node.getTermina() != null)
        {
            node.getTermina().apply(this);
        }
        outADefClasseDefClasse(node);
    }

    public void inAAtributosAtributos(AAtributosAtributos node)
    {
        defaultIn(node);
    }

    public void outAAtributosAtributos(AAtributosAtributos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtributosAtributos(AAtributosAtributos node)
    {
        inAAtributosAtributos(node);
        if(node.getDec() != null)
        {
            node.getDec().apply(this);
        }
        if(node.getAtributos() != null)
        {
            node.getAtributos().apply(this);
        }
        outAAtributosAtributos(node);
    }

    public void inAVazioAtributos(AVazioAtributos node)
    {
        defaultIn(node);
    }

    public void outAVazioAtributos(AVazioAtributos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVazioAtributos(AVazioAtributos node)
    {
        inAVazioAtributos(node);
        outAVazioAtributos(node);
    }

    public void inAMetodosMetodos(AMetodosMetodos node)
    {
        defaultIn(node);
    }

    public void outAMetodosMetodos(AMetodosMetodos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMetodosMetodos(AMetodosMetodos node)
    {
        inAMetodosMetodos(node);
        if(node.getDec2() != null)
        {
            node.getDec2().apply(this);
        }
        if(node.getMetodos() != null)
        {
            node.getMetodos().apply(this);
        }
        outAMetodosMetodos(node);
    }

    public void inAVazioMetodos(AVazioMetodos node)
    {
        defaultIn(node);
    }

    public void outAVazioMetodos(AVazioMetodos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVazioMetodos(AVazioMetodos node)
    {
        inAVazioMetodos(node);
        outAVazioMetodos(node);
    }

    public void inAObjDec(AObjDec node)
    {
        defaultIn(node);
    }

    public void outAObjDec(AObjDec node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAObjDec(AObjDec node)
    {
        inAObjDec(node);
        if(node.getDecObj() != null)
        {
            node.getDecObj().apply(this);
        }
        outAObjDec(node);
    }

    public void inAVarDec(AVarDec node)
    {
        defaultIn(node);
    }

    public void outAVarDec(AVarDec node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarDec(AVarDec node)
    {
        inAVarDec(node);
        if(node.getDecVar() != null)
        {
            node.getDecVar().apply(this);
        }
        outAVarDec(node);
    }

    public void inAConsDec(AConsDec node)
    {
        defaultIn(node);
    }

    public void outAConsDec(AConsDec node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConsDec(AConsDec node)
    {
        inAConsDec(node);
        if(node.getDecCons() != null)
        {
            node.getDecCons().apply(this);
        }
        outAConsDec(node);
    }

    public void inAListaDecListaDecs(AListaDecListaDecs node)
    {
        defaultIn(node);
    }

    public void outAListaDecListaDecs(AListaDecListaDecs node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaDecListaDecs(AListaDecListaDecs node)
    {
        inAListaDecListaDecs(node);
        if(node.getDec() != null)
        {
            node.getDec().apply(this);
        }
        if(node.getListaDecs() != null)
        {
            node.getListaDecs().apply(this);
        }
        outAListaDecListaDecs(node);
    }

    public void inAVazioListaDecs(AVazioListaDecs node)
    {
        defaultIn(node);
    }

    public void outAVazioListaDecs(AVazioListaDecs node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVazioListaDecs(AVazioListaDecs node)
    {
        inAVazioListaDecs(node);
        outAVazioListaDecs(node);
    }

    public void inADecObjDecObj(ADecObjDecObj node)
    {
        defaultIn(node);
    }

    public void outADecObjDecObj(ADecObjDecObj node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecObjDecObj(ADecObjDecObj node)
    {
        inADecObjDecObj(node);
        if(node.getObjeto() != null)
        {
            node.getObjeto().apply(this);
        }
        if(node.getCid() != null)
        {
            node.getCid().apply(this);
        }
        if(node.getListaId() != null)
        {
            node.getListaId().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outADecObjDecObj(node);
    }

    public void inADecVarDecVar(ADecVarDecVar node)
    {
        defaultIn(node);
    }

    public void outADecVarDecVar(ADecVarDecVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecVarDecVar(ADecVarDecVar node)
    {
        inADecVarDecVar(node);
        if(node.getVariavel() != null)
        {
            node.getVariavel().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getListaId() != null)
        {
            node.getListaId().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outADecVarDecVar(node);
    }

    public void inADecConsDecCons(ADecConsDecCons node)
    {
        defaultIn(node);
    }

    public void outADecConsDecCons(ADecConsDecCons node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecConsDecCons(ADecConsDecCons node)
    {
        inADecConsDecCons(node);
        if(node.getConstante() != null)
        {
            node.getConstante().apply(this);
        }
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        if(node.getListaInicializacao() != null)
        {
            node.getListaInicializacao().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outADecConsDecCons(node);
    }

    public void inAInicializacaoInicializacao(AInicializacaoInicializacao node)
    {
        defaultIn(node);
    }

    public void outAInicializacaoInicializacao(AInicializacaoInicializacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInicializacaoInicializacao(AInicializacaoInicializacao node)
    {
        inAInicializacaoInicializacao(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getInicializacao() != null)
        {
            node.getInicializacao().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAInicializacaoInicializacao(node);
    }

    public void inAListaIdListaId(AListaIdListaId node)
    {
        defaultIn(node);
    }

    public void outAListaIdListaId(AListaIdListaId node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaIdListaId(AListaIdListaId node)
    {
        inAListaIdListaId(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        if(node.getListaId() != null)
        {
            node.getListaId().apply(this);
        }
        outAListaIdListaId(node);
    }

    public void inAIdListaId(AIdListaId node)
    {
        defaultIn(node);
    }

    public void outAIdListaId(AIdListaId node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdListaId(AIdListaId node)
    {
        inAIdListaId(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAIdListaId(node);
    }

    public void inAListaInicializacaoListaInicializacao(AListaInicializacaoListaInicializacao node)
    {
        defaultIn(node);
    }

    public void outAListaInicializacaoListaInicializacao(AListaInicializacaoListaInicializacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaInicializacaoListaInicializacao(AListaInicializacaoListaInicializacao node)
    {
        inAListaInicializacaoListaInicializacao(node);
        if(node.getInicializacao() != null)
        {
            node.getInicializacao().apply(this);
        }
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        if(node.getListaInicializacao() != null)
        {
            node.getListaInicializacao().apply(this);
        }
        outAListaInicializacaoListaInicializacao(node);
    }

    public void inAInicializacaoListaInicializacao(AInicializacaoListaInicializacao node)
    {
        defaultIn(node);
    }

    public void outAInicializacaoListaInicializacao(AInicializacaoListaInicializacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInicializacaoListaInicializacao(AInicializacaoListaInicializacao node)
    {
        inAInicializacaoListaInicializacao(node);
        if(node.getInicializacao() != null)
        {
            node.getInicializacao().apply(this);
        }
        outAInicializacaoListaInicializacao(node);
    }

    public void inAClasseTipo(AClasseTipo node)
    {
        defaultIn(node);
    }

    public void outAClasseTipo(AClasseTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAClasseTipo(AClasseTipo node)
    {
        inAClasseTipo(node);
        if(node.getTipoClasse() != null)
        {
            node.getTipoClasse().apply(this);
        }
        outAClasseTipo(node);
    }

    public void inAPrimitivoTipo(APrimitivoTipo node)
    {
        defaultIn(node);
    }

    public void outAPrimitivoTipo(APrimitivoTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrimitivoTipo(APrimitivoTipo node)
    {
        inAPrimitivoTipo(node);
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        outAPrimitivoTipo(node);
    }

    public void inAIntTipoPrimitivo(AIntTipoPrimitivo node)
    {
        defaultIn(node);
    }

    public void outAIntTipoPrimitivo(AIntTipoPrimitivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntTipoPrimitivo(AIntTipoPrimitivo node)
    {
        inAIntTipoPrimitivo(node);
        if(node.getInt() != null)
        {
            node.getInt().apply(this);
        }
        outAIntTipoPrimitivo(node);
    }

    public void inABoolTipoPrimitivo(ABoolTipoPrimitivo node)
    {
        defaultIn(node);
    }

    public void outABoolTipoPrimitivo(ABoolTipoPrimitivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABoolTipoPrimitivo(ABoolTipoPrimitivo node)
    {
        inABoolTipoPrimitivo(node);
        if(node.getBool() != null)
        {
            node.getBool().apply(this);
        }
        outABoolTipoPrimitivo(node);
    }

    public void inARealTipoPrimitivo(ARealTipoPrimitivo node)
    {
        defaultIn(node);
    }

    public void outARealTipoPrimitivo(ARealTipoPrimitivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARealTipoPrimitivo(ARealTipoPrimitivo node)
    {
        inARealTipoPrimitivo(node);
        if(node.getReal() != null)
        {
            node.getReal().apply(this);
        }
        outARealTipoPrimitivo(node);
    }

    public void inATipoClasseTipoClasse(ATipoClasseTipoClasse node)
    {
        defaultIn(node);
    }

    public void outATipoClasseTipoClasse(ATipoClasseTipoClasse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoClasseTipoClasse(ATipoClasseTipoClasse node)
    {
        inATipoClasseTipoClasse(node);
        if(node.getCid() != null)
        {
            node.getCid().apply(this);
        }
        outATipoClasseTipoClasse(node);
    }

    public void inAProcDec2(AProcDec2 node)
    {
        defaultIn(node);
    }

    public void outAProcDec2(AProcDec2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProcDec2(AProcDec2 node)
    {
        inAProcDec2(node);
        if(node.getDecProcedimento() != null)
        {
            node.getDecProcedimento().apply(this);
        }
        outAProcDec2(node);
    }

    public void inAFuncDec2(AFuncDec2 node)
    {
        defaultIn(node);
    }

    public void outAFuncDec2(AFuncDec2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncDec2(AFuncDec2 node)
    {
        inAFuncDec2(node);
        if(node.getDecFuncao() != null)
        {
            node.getDecFuncao().apply(this);
        }
        outAFuncDec2(node);
    }

    public void inADecProcedimentoDecProcedimento(ADecProcedimentoDecProcedimento node)
    {
        defaultIn(node);
    }

    public void outADecProcedimentoDecProcedimento(ADecProcedimentoDecProcedimento node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecProcedimentoDecProcedimento(ADecProcedimentoDecProcedimento node)
    {
        inADecProcedimentoDecProcedimento(node);
        if(node.getPontoDeEntrada() != null)
        {
            node.getPontoDeEntrada().apply(this);
        }
        if(node.getProcedimento() != null)
        {
            node.getProcedimento().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getParentesesEsquerdo() != null)
        {
            node.getParentesesEsquerdo().apply(this);
        }
        if(node.getParametros() != null)
        {
            node.getParametros().apply(this);
        }
        if(node.getParentesesDireito() != null)
        {
            node.getParentesesDireito().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outADecProcedimentoDecProcedimento(node);
    }

    public void inADecFuncaoDecFuncao(ADecFuncaoDecFuncao node)
    {
        defaultIn(node);
    }

    public void outADecFuncaoDecFuncao(ADecFuncaoDecFuncao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecFuncaoDecFuncao(ADecFuncaoDecFuncao node)
    {
        inADecFuncaoDecFuncao(node);
        if(node.getFuncao() != null)
        {
            node.getFuncao().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getParentesesEsquerdo() != null)
        {
            node.getParentesesEsquerdo().apply(this);
        }
        if(node.getParametros() != null)
        {
            node.getParametros().apply(this);
        }
        if(node.getParentesesDireito() != null)
        {
            node.getParentesesDireito().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outADecFuncaoDecFuncao(node);
    }

    public void inAParametrosParametros(AParametrosParametros node)
    {
        defaultIn(node);
    }

    public void outAParametrosParametros(AParametrosParametros node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametrosParametros(AParametrosParametros node)
    {
        inAParametrosParametros(node);
        if(node.getListaParametro() != null)
        {
            node.getListaParametro().apply(this);
        }
        outAParametrosParametros(node);
    }

    public void inAVazioParametros(AVazioParametros node)
    {
        defaultIn(node);
    }

    public void outAVazioParametros(AVazioParametros node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVazioParametros(AVazioParametros node)
    {
        inAVazioParametros(node);
        outAVazioParametros(node);
    }

    public void inAListaParametroListaParametro(AListaParametroListaParametro node)
    {
        defaultIn(node);
    }

    public void outAListaParametroListaParametro(AListaParametroListaParametro node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaParametroListaParametro(AListaParametroListaParametro node)
    {
        inAListaParametroListaParametro(node);
        if(node.getParametro() != null)
        {
            node.getParametro().apply(this);
        }
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        if(node.getListaParametro() != null)
        {
            node.getListaParametro().apply(this);
        }
        outAListaParametroListaParametro(node);
    }

    public void inAParametroListaParametro(AParametroListaParametro node)
    {
        defaultIn(node);
    }

    public void outAParametroListaParametro(AParametroListaParametro node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametroListaParametro(AParametroListaParametro node)
    {
        inAParametroListaParametro(node);
        if(node.getParametro() != null)
        {
            node.getParametro().apply(this);
        }
        outAParametroListaParametro(node);
    }

    public void inAParametroParametro(AParametroParametro node)
    {
        defaultIn(node);
    }

    public void outAParametroParametro(AParametroParametro node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametroParametro(AParametroParametro node)
    {
        inAParametroParametro(node);
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAParametroParametro(node);
    }

    public void inACondComando(ACondComando node)
    {
        defaultIn(node);
    }

    public void outACondComando(ACondComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACondComando(ACondComando node)
    {
        inACondComando(node);
        if(node.getSe() != null)
        {
            node.getSe().apply(this);
        }
        if(node.getParentesesEsquerdo() != null)
        {
            node.getParentesesEsquerdo().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParentesesDireito() != null)
        {
            node.getParentesesDireito().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outACondComando(node);
    }

    public void inACondElseComando(ACondElseComando node)
    {
        defaultIn(node);
    }

    public void outACondElseComando(ACondElseComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACondElseComando(ACondElseComando node)
    {
        inACondElseComando(node);
        if(node.getSe() != null)
        {
            node.getSe().apply(this);
        }
        if(node.getParentesesEsquerdo() != null)
        {
            node.getParentesesEsquerdo().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParentesesDireito() != null)
        {
            node.getParentesesDireito().apply(this);
        }
        if(node.getComandoElse() != null)
        {
            node.getComandoElse().apply(this);
        }
        if(node.getSenao() != null)
        {
            node.getSenao().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outACondElseComando(node);
    }

    public void inALoopComando(ALoopComando node)
    {
        defaultIn(node);
    }

    public void outALoopComando(ALoopComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALoopComando(ALoopComando node)
    {
        inALoopComando(node);
        if(node.getEnquanto() != null)
        {
            node.getEnquanto().apply(this);
        }
        if(node.getParentesesEsquerdo() != null)
        {
            node.getParentesesEsquerdo().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParentesesDireito() != null)
        {
            node.getParentesesDireito().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outALoopComando(node);
    }

    public void inAAtribComando(AAtribComando node)
    {
        defaultIn(node);
    }

    public void outAAtribComando(AAtribComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribComando(AAtribComando node)
    {
        inAAtribComando(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getAtribuicao() != null)
        {
            node.getAtribuicao().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAAtribComando(node);
    }

    public void inACallComando(ACallComando node)
    {
        defaultIn(node);
    }

    public void outACallComando(ACallComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACallComando(ACallComando node)
    {
        inACallComando(node);
        if(node.getIdPonto() != null)
        {
            node.getIdPonto().apply(this);
        }
        if(node.getChamada() != null)
        {
            node.getChamada().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outACallComando(node);
    }

    public void inABlocoComando(ABlocoComando node)
    {
        defaultIn(node);
    }

    public void outABlocoComando(ABlocoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoComando(ABlocoComando node)
    {
        inABlocoComando(node);
        if(node.getBloco() != null)
        {
            node.getBloco().apply(this);
        }
        outABlocoComando(node);
    }

    public void inACondComandoElse(ACondComandoElse node)
    {
        defaultIn(node);
    }

    public void outACondComandoElse(ACondComandoElse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACondComandoElse(ACondComandoElse node)
    {
        inACondComandoElse(node);
        if(node.getSe() != null)
        {
            node.getSe().apply(this);
        }
        if(node.getParentesesEsquerdo() != null)
        {
            node.getParentesesEsquerdo().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParentesesDireito() != null)
        {
            node.getParentesesDireito().apply(this);
        }
        if(node.getComandoElse() != null)
        {
            node.getComandoElse().apply(this);
        }
        if(node.getContComandoElse() != null)
        {
            node.getContComandoElse().apply(this);
        }
        outACondComandoElse(node);
    }

    public void inALoopComandoElse(ALoopComandoElse node)
    {
        defaultIn(node);
    }

    public void outALoopComandoElse(ALoopComandoElse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALoopComandoElse(ALoopComandoElse node)
    {
        inALoopComandoElse(node);
        if(node.getEnquanto() != null)
        {
            node.getEnquanto().apply(this);
        }
        if(node.getParentesesEsquerdo() != null)
        {
            node.getParentesesEsquerdo().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParentesesDireito() != null)
        {
            node.getParentesesDireito().apply(this);
        }
        if(node.getComandoElse() != null)
        {
            node.getComandoElse().apply(this);
        }
        outALoopComandoElse(node);
    }

    public void inAAtribComandoElse(AAtribComandoElse node)
    {
        defaultIn(node);
    }

    public void outAAtribComandoElse(AAtribComandoElse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribComandoElse(AAtribComandoElse node)
    {
        inAAtribComandoElse(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getAtribuicao() != null)
        {
            node.getAtribuicao().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAAtribComandoElse(node);
    }

    public void inACallComandoElse(ACallComandoElse node)
    {
        defaultIn(node);
    }

    public void outACallComandoElse(ACallComandoElse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACallComandoElse(ACallComandoElse node)
    {
        inACallComandoElse(node);
        if(node.getIdPonto() != null)
        {
            node.getIdPonto().apply(this);
        }
        if(node.getChamada() != null)
        {
            node.getChamada().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outACallComandoElse(node);
    }

    public void inABlocoComandoElse(ABlocoComandoElse node)
    {
        defaultIn(node);
    }

    public void outABlocoComandoElse(ABlocoComandoElse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoComandoElse(ABlocoComandoElse node)
    {
        inABlocoComandoElse(node);
        if(node.getBloco() != null)
        {
            node.getBloco().apply(this);
        }
        outABlocoComandoElse(node);
    }

    public void inAContCondContComandoElse(AContCondContComandoElse node)
    {
        defaultIn(node);
    }

    public void outAContCondContComandoElse(AContCondContComandoElse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAContCondContComandoElse(AContCondContComandoElse node)
    {
        inAContCondContComandoElse(node);
        if(node.getSenao() != null)
        {
            node.getSenao().apply(this);
        }
        if(node.getComandoElse() != null)
        {
            node.getComandoElse().apply(this);
        }
        outAContCondContComandoElse(node);
    }

    public void inAListaComandosListaComandos(AListaComandosListaComandos node)
    {
        defaultIn(node);
    }

    public void outAListaComandosListaComandos(AListaComandosListaComandos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaComandosListaComandos(AListaComandosListaComandos node)
    {
        inAListaComandosListaComandos(node);
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getListaComandos() != null)
        {
            node.getListaComandos().apply(this);
        }
        outAListaComandosListaComandos(node);
    }

    public void inAVazioListaComandos(AVazioListaComandos node)
    {
        defaultIn(node);
    }

    public void outAVazioListaComandos(AVazioListaComandos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVazioListaComandos(AVazioListaComandos node)
    {
        inAVazioListaComandos(node);
        outAVazioListaComandos(node);
    }

    public void inABlocoBloco(ABlocoBloco node)
    {
        defaultIn(node);
    }

    public void outABlocoBloco(ABlocoBloco node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoBloco(ABlocoBloco node)
    {
        inABlocoBloco(node);
        if(node.getComeca() != null)
        {
            node.getComeca().apply(this);
        }
        if(node.getListaDecs() != null)
        {
            node.getListaDecs().apply(this);
        }
        if(node.getListaComandos() != null)
        {
            node.getListaComandos().apply(this);
        }
        if(node.getTermina() != null)
        {
            node.getTermina().apply(this);
        }
        outABlocoBloco(node);
    }

    public void inACondExp(ACondExp node)
    {
        defaultIn(node);
    }

    public void outACondExp(ACondExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACondExp(ACondExp node)
    {
        inACondExp(node);
        if(node.getSe() != null)
        {
            node.getSe().apply(this);
        }
        if(node.getParentesesEsquerdo() != null)
        {
            node.getParentesesEsquerdo().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParentesesDireito() != null)
        {
            node.getParentesesDireito().apply(this);
        }
        if(node.getEntao() != null)
        {
            node.getEntao().apply(this);
        }
        if(node.getCondExp2() != null)
        {
            node.getCondExp2().apply(this);
        }
        outACondExp(node);
    }

    public void inANegativoExp(ANegativoExp node)
    {
        defaultIn(node);
    }

    public void outANegativoExp(ANegativoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANegativoExp(ANegativoExp node)
    {
        inANegativoExp(node);
        if(node.getSubtracao() != null)
        {
            node.getSubtracao().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outANegativoExp(node);
    }

    public void inASomaExp(ASomaExp node)
    {
        defaultIn(node);
    }

    public void outASomaExp(ASomaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASomaExp(ASomaExp node)
    {
        inASomaExp(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        if(node.getAdicao() != null)
        {
            node.getAdicao().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outASomaExp(node);
    }

    public void inASubtExp(ASubtExp node)
    {
        defaultIn(node);
    }

    public void outASubtExp(ASubtExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASubtExp(ASubtExp node)
    {
        inASubtExp(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        if(node.getSubtracao() != null)
        {
            node.getSubtracao().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outASubtExp(node);
    }

    public void inAMultiExp(AMultiExp node)
    {
        defaultIn(node);
    }

    public void outAMultiExp(AMultiExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiExp(AMultiExp node)
    {
        inAMultiExp(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        if(node.getMultiplicacao() != null)
        {
            node.getMultiplicacao().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAMultiExp(node);
    }

    public void inADivExp(ADivExp node)
    {
        defaultIn(node);
    }

    public void outADivExp(ADivExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivExp(ADivExp node)
    {
        inADivExp(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        if(node.getDivisao() != null)
        {
            node.getDivisao().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outADivExp(node);
    }

    public void inAModExp(AModExp node)
    {
        defaultIn(node);
    }

    public void outAModExp(AModExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAModExp(AModExp node)
    {
        inAModExp(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        if(node.getModulo() != null)
        {
            node.getModulo().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAModExp(node);
    }

    public void inAIgualExp(AIgualExp node)
    {
        defaultIn(node);
    }

    public void outAIgualExp(AIgualExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIgualExp(AIgualExp node)
    {
        inAIgualExp(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        if(node.getIgualdade() != null)
        {
            node.getIgualdade().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAIgualExp(node);
    }

    public void inAMenorExp(AMenorExp node)
    {
        defaultIn(node);
    }

    public void outAMenorExp(AMenorExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorExp(AMenorExp node)
    {
        inAMenorExp(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        if(node.getMenorQue() != null)
        {
            node.getMenorQue().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAMenorExp(node);
    }

    public void inADifExp(ADifExp node)
    {
        defaultIn(node);
    }

    public void outADifExp(ADifExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADifExp(ADifExp node)
    {
        inADifExp(node);
        if(node.getNegacao() != null)
        {
            node.getNegacao().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outADifExp(node);
    }

    public void inAAndExp(AAndExp node)
    {
        defaultIn(node);
    }

    public void outAAndExp(AAndExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAndExp(AAndExp node)
    {
        inAAndExp(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        if(node.getE() != null)
        {
            node.getE().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAAndExp(node);
    }

    public void inAOrExp(AOrExp node)
    {
        defaultIn(node);
    }

    public void outAOrExp(AOrExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrExp(AOrExp node)
    {
        inAOrExp(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        if(node.getOu() != null)
        {
            node.getOu().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAOrExp(node);
    }

    public void inABlocoExpExp(ABlocoExpExp node)
    {
        defaultIn(node);
    }

    public void outABlocoExpExp(ABlocoExpExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoExpExp(ABlocoExpExp node)
    {
        inABlocoExpExp(node);
        if(node.getBlocoExp() != null)
        {
            node.getBlocoExp().apply(this);
        }
        outABlocoExpExp(node);
    }

    public void inATermoExp(ATermoExp node)
    {
        defaultIn(node);
    }

    public void outATermoExp(ATermoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATermoExp(ATermoExp node)
    {
        inATermoExp(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outATermoExp(node);
    }

    public void inAContCondCondExp2(AContCondCondExp2 node)
    {
        defaultIn(node);
    }

    public void outAContCondCondExp2(AContCondCondExp2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAContCondCondExp2(AContCondCondExp2 node)
    {
        inAContCondCondExp2(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getCondExp3() != null)
        {
            node.getCondExp3().apply(this);
        }
        outAContCondCondExp2(node);
    }

    public void inAFimCondCondExp3(AFimCondCondExp3 node)
    {
        defaultIn(node);
    }

    public void outAFimCondCondExp3(AFimCondCondExp3 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFimCondCondExp3(AFimCondCondExp3 node)
    {
        inAFimCondCondExp3(node);
        if(node.getSenao() != null)
        {
            node.getSenao().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAFimCondCondExp3(node);
    }

    public void inAInteiroTermo(AInteiroTermo node)
    {
        defaultIn(node);
    }

    public void outAInteiroTermo(AInteiroTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInteiroTermo(AInteiroTermo node)
    {
        inAInteiroTermo(node);
        if(node.getNumeroInteiro() != null)
        {
            node.getNumeroInteiro().apply(this);
        }
        outAInteiroTermo(node);
    }

    public void inARealTermo(ARealTermo node)
    {
        defaultIn(node);
    }

    public void outARealTermo(ARealTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARealTermo(ARealTermo node)
    {
        inARealTermo(node);
        if(node.getNumeroReal() != null)
        {
            node.getNumeroReal().apply(this);
        }
        outARealTermo(node);
    }

    public void inATrueTermo(ATrueTermo node)
    {
        defaultIn(node);
    }

    public void outATrueTermo(ATrueTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATrueTermo(ATrueTermo node)
    {
        inATrueTermo(node);
        if(node.getTrue() != null)
        {
            node.getTrue().apply(this);
        }
        outATrueTermo(node);
    }

    public void inAFalseTermo(AFalseTermo node)
    {
        defaultIn(node);
    }

    public void outAFalseTermo(AFalseTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFalseTermo(AFalseTermo node)
    {
        inAFalseTermo(node);
        if(node.getFalse() != null)
        {
            node.getFalse().apply(this);
        }
        outAFalseTermo(node);
    }

    public void inAIdCallTermo(AIdCallTermo node)
    {
        defaultIn(node);
    }

    public void outAIdCallTermo(AIdCallTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdCallTermo(AIdCallTermo node)
    {
        inAIdCallTermo(node);
        if(node.getIdCall() != null)
        {
            node.getIdCall().apply(this);
        }
        outAIdCallTermo(node);
    }

    public void inAParTermo(AParTermo node)
    {
        defaultIn(node);
    }

    public void outAParTermo(AParTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParTermo(AParTermo node)
    {
        inAParTermo(node);
        if(node.getParentesesEsquerdo() != null)
        {
            node.getParentesesEsquerdo().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParentesesDireito() != null)
        {
            node.getParentesesDireito().apply(this);
        }
        outAParTermo(node);
    }

    public void inAIdIdCall(AIdIdCall node)
    {
        defaultIn(node);
    }

    public void outAIdIdCall(AIdIdCall node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdIdCall(AIdIdCall node)
    {
        inAIdIdCall(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAIdIdCall(node);
    }

    public void inACallIdCall(ACallIdCall node)
    {
        defaultIn(node);
    }

    public void outACallIdCall(ACallIdCall node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACallIdCall(ACallIdCall node)
    {
        inACallIdCall(node);
        if(node.getIdPonto() != null)
        {
            node.getIdPonto().apply(this);
        }
        if(node.getChamada() != null)
        {
            node.getChamada().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outACallIdCall(node);
    }

    public void inAAtribIdCall(AAtribIdCall node)
    {
        defaultIn(node);
    }

    public void outAAtribIdCall(AAtribIdCall node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribIdCall(AAtribIdCall node)
    {
        inAAtribIdCall(node);
        if(node.getIdPonto() != null)
        {
            node.getIdPonto().apply(this);
        }
        if(node.getAtributo() != null)
        {
            node.getAtributo().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAAtribIdCall(node);
    }

    public void inAIdPontoIdPonto(AIdPontoIdPonto node)
    {
        defaultIn(node);
    }

    public void outAIdPontoIdPonto(AIdPontoIdPonto node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdPontoIdPonto(AIdPontoIdPonto node)
    {
        inAIdPontoIdPonto(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        outAIdPontoIdPonto(node);
    }

    public void inABlocoExpBlocoExp(ABlocoExpBlocoExp node)
    {
        defaultIn(node);
    }

    public void outABlocoExpBlocoExp(ABlocoExpBlocoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoExpBlocoExp(ABlocoExpBlocoExp node)
    {
        inABlocoExpBlocoExp(node);
        if(node.getComeca() != null)
        {
            node.getComeca().apply(this);
        }
        if(node.getListaDecCons() != null)
        {
            node.getListaDecCons().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getTermina() != null)
        {
            node.getTermina().apply(this);
        }
        outABlocoExpBlocoExp(node);
    }

    public void inAListaDecConsListaDecCons(AListaDecConsListaDecCons node)
    {
        defaultIn(node);
    }

    public void outAListaDecConsListaDecCons(AListaDecConsListaDecCons node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaDecConsListaDecCons(AListaDecConsListaDecCons node)
    {
        inAListaDecConsListaDecCons(node);
        if(node.getDecCons() != null)
        {
            node.getDecCons().apply(this);
        }
        if(node.getListaDecCons() != null)
        {
            node.getListaDecCons().apply(this);
        }
        outAListaDecConsListaDecCons(node);
    }

    public void inAVazioListaDecCons(AVazioListaDecCons node)
    {
        defaultIn(node);
    }

    public void outAVazioListaDecCons(AVazioListaDecCons node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVazioListaDecCons(AVazioListaDecCons node)
    {
        inAVazioListaDecCons(node);
        outAVazioListaDecCons(node);
    }

    public void inAChamadaChamada(AChamadaChamada node)
    {
        defaultIn(node);
    }

    public void outAChamadaChamada(AChamadaChamada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaChamada(AChamadaChamada node)
    {
        inAChamadaChamada(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getParentesesEsquerdo() != null)
        {
            node.getParentesesEsquerdo().apply(this);
        }
        if(node.getListaExp() != null)
        {
            node.getListaExp().apply(this);
        }
        if(node.getParentesesDireito() != null)
        {
            node.getParentesesDireito().apply(this);
        }
        outAChamadaChamada(node);
    }

    public void inAListaExpListaExp(AListaExpListaExp node)
    {
        defaultIn(node);
    }

    public void outAListaExpListaExp(AListaExpListaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaExpListaExp(AListaExpListaExp node)
    {
        inAListaExpListaExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        if(node.getListaExp() != null)
        {
            node.getListaExp().apply(this);
        }
        outAListaExpListaExp(node);
    }

    public void inAExpListaExp(AExpListaExp node)
    {
        defaultIn(node);
    }

    public void outAExpListaExp(AExpListaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpListaExp(AExpListaExp node)
    {
        inAExpListaExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAExpListaExp(node);
    }

    public void inAVazioListaExp(AVazioListaExp node)
    {
        defaultIn(node);
    }

    public void outAVazioListaExp(AVazioListaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVazioListaExp(AVazioListaExp node)
    {
        inAVazioListaExp(node);
        outAVazioListaExp(node);
    }

    public void inAVazioAtributo(AVazioAtributo node)
    {
        defaultIn(node);
    }

    public void outAVazioAtributo(AVazioAtributo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVazioAtributo(AVazioAtributo node)
    {
        inAVazioAtributo(node);
        outAVazioAtributo(node);
    }
}
