/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.parser;

import quase.node.*;
import quase.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTEComercial(TEComercial node)
    {
        index = 0;
    }

    public void caseTPontoVirgula(TPontoVirgula node)
    {
        index = 1;
    }

    public void caseTClasse(TClasse node)
    {
        index = 2;
    }

    public void caseTFilhaDaClasse(TFilhaDaClasse node)
    {
        index = 3;
    }

    public void caseTComeca(TComeca node)
    {
        index = 4;
    }

    public void caseTTermina(TTermina node)
    {
        index = 5;
    }

    public void caseTObjeto(TObjeto node)
    {
        index = 6;
    }

    public void caseTVirgula(TVirgula node)
    {
        index = 7;
    }

    public void caseTVariavel(TVariavel node)
    {
        index = 8;
    }

    public void caseTConstante(TConstante node)
    {
        index = 9;
    }

    public void caseTInicializacao(TInicializacao node)
    {
        index = 10;
    }

    public void caseTInt(TInt node)
    {
        index = 11;
    }

    public void caseTBool(TBool node)
    {
        index = 12;
    }

    public void caseTReal(TReal node)
    {
        index = 13;
    }

    public void caseTPontoDeEntrada(TPontoDeEntrada node)
    {
        index = 14;
    }

    public void caseTProcedimento(TProcedimento node)
    {
        index = 15;
    }

    public void caseTParentesesEsquerdo(TParentesesEsquerdo node)
    {
        index = 16;
    }

    public void caseTParentesesDireito(TParentesesDireito node)
    {
        index = 17;
    }

    public void caseTFuncao(TFuncao node)
    {
        index = 18;
    }

    public void caseTSe(TSe node)
    {
        index = 19;
    }

    public void caseTSenao(TSenao node)
    {
        index = 20;
    }

    public void caseTEnquanto(TEnquanto node)
    {
        index = 21;
    }

    public void caseTAtribuicao(TAtribuicao node)
    {
        index = 22;
    }

    public void caseTPonto(TPonto node)
    {
        index = 23;
    }

    public void caseTTrue(TTrue node)
    {
        index = 24;
    }

    public void caseTFalse(TFalse node)
    {
        index = 25;
    }

    public void caseTSubtracao(TSubtracao node)
    {
        index = 26;
    }

    public void caseTEntao(TEntao node)
    {
        index = 27;
    }

    public void caseTAdicao(TAdicao node)
    {
        index = 28;
    }

    public void caseTMultiplicacao(TMultiplicacao node)
    {
        index = 29;
    }

    public void caseTDivisao(TDivisao node)
    {
        index = 30;
    }

    public void caseTModulo(TModulo node)
    {
        index = 31;
    }

    public void caseTIgualdade(TIgualdade node)
    {
        index = 32;
    }

    public void caseTMenorQue(TMenorQue node)
    {
        index = 33;
    }

    public void caseTNegacao(TNegacao node)
    {
        index = 34;
    }

    public void caseTE(TE node)
    {
        index = 35;
    }

    public void caseTOu(TOu node)
    {
        index = 36;
    }

    public void caseTId(TId node)
    {
        index = 37;
    }

    public void caseTCid(TCid node)
    {
        index = 38;
    }

    public void caseTNumeroInteiro(TNumeroInteiro node)
    {
        index = 39;
    }

    public void caseTNumeroReal(TNumeroReal node)
    {
        index = 40;
    }

    public void caseEOF(EOF node)
    {
        index = 41;
    }
}
