/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.lexer;

import java.io.*;
import quase.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEComercial(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoVirgula(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TClasse(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFilhaDaClasse(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComeca(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTermina(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TObjeto(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVirgula(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVariavel(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConstante(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicializacao(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInt(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBool(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReal(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoDeEntrada(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProcedimento(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParentesesEsquerdo(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParentesesDireito(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFuncao(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSe(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSenao(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnquanto(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtribuicao(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPonto(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTrue(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalse(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSubtracao(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEntao(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAdicao(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMultiplicacao(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDivisao(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TModulo(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgualdade(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorQue(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNegacao(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TE(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOu(line, pos); }
    Token new37(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentario(text, line, pos); }
    Token new38(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }
    Token new39(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCid(text, line, pos); }
    Token new40(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumeroInteiro(text, line, pos); }
    Token new41(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumeroReal(text, line, pos); }
    Token new42(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVazio(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {37, 37, 6}, {38, 38, 7}, {40, 40, 8}, {41, 41, 9}, {42, 42, 10}, {43, 43, 11}, {44, 44, 12}, {45, 45, 13}, {46, 46, 14}, {47, 47, 15}, {48, 48, 16}, {49, 57, 17}, {58, 58, 18}, {59, 59, 19}, {60, 60, 20}, {61, 61, 21}, {65, 90, 22}, {95, 95, 23}, {97, 97, 24}, {98, 98, 25}, {99, 99, 26}, {100, 100, 24}, {101, 101, 27}, {102, 102, 28}, {103, 104, 24}, {105, 105, 29}, {106, 110, 24}, {111, 111, 30}, {112, 112, 31}, {113, 113, 24}, {114, 114, 32}, {115, 115, 33}, {116, 116, 34}, {117, 117, 24}, {118, 118, 35}, {119, 122, 24}, {123, 123, 36}, {192, 195, 37}, {199, 199, 38}, {201, 201, 39}, {202, 202, 40}, {205, 205, 41}, {211, 213, 42}, {218, 218, 43}, {224, 227, 44}, {231, 231, 45}, {233, 233, 46}, {234, 234, 47}, {237, 237, 48}, {243, 245, 49}, {250, 250, 50}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {{46, 46, 51}, {48, 57, 52}, {98, 98, 53}, },
            {{46, 46, 54}, {48, 57, 52}, {69, 69, 55}, {101, 101, 56}, },
            {{61, 61, 57}, },
            {},
            {},
            {{61, 61, 58}, {62, 62, 59}, },
            {{65, 90, 60}, {95, 95, 61}, {97, 122, 62}, {192, 195, 63}, {199, 199, 64}, {201, 201, 65}, {202, 202, 66}, {205, 205, 67}, {211, 213, 68}, {218, 218, 69}, {224, 227, 70}, {231, 231, 71}, {233, 233, 72}, {234, 234, 73}, {237, 237, 74}, {243, 245, 75}, {250, 250, 76}, },
            {{65, 90, 77}, {95, 95, 78}, {97, 122, 79}, {192, 195, 80}, {199, 199, 81}, {201, 201, 82}, {202, 202, 83}, {205, 205, 84}, {211, 213, 85}, {218, 218, 86}, {224, 227, 87}, {231, 231, 88}, {233, 233, 89}, {234, 234, 90}, {237, 237, 91}, {243, 245, 92}, {250, 250, 93}, },
            {{65, 250, -24}, },
            {{65, 95, -24}, {97, 110, 62}, {111, 111, 94}, {112, 122, 62}, {192, 250, -24}, },
            {{65, 95, -24}, {97, 107, 62}, {108, 108, 95}, {109, 110, 62}, {111, 111, 96}, {112, 250, -27}, },
            {{65, 95, -24}, {97, 109, 62}, {110, 110, 97}, {111, 122, 62}, {192, 250, -24}, },
            {{65, 95, -24}, {97, 97, 98}, {98, 104, 62}, {105, 105, 99}, {106, 116, 62}, {117, 117, 100}, {118, 122, 62}, {192, 250, -24}, },
            {{65, 109, -29}, {110, 110, 101}, {111, 250, -29}, },
            {{65, 95, -24}, {97, 97, 62}, {98, 98, 102}, {99, 116, 62}, {117, 117, 103}, {118, 250, -30}, },
            {{65, 95, -24}, {97, 113, 62}, {114, 114, 104}, {115, 122, 62}, {192, 250, -24}, },
            {{65, 95, -24}, {97, 100, 62}, {101, 101, 105}, {102, 122, 62}, {192, 250, -24}, },
            {{65, 100, -34}, {101, 101, 106}, {102, 250, -34}, },
            {{65, 100, -34}, {101, 101, 107}, {102, 113, 62}, {114, 114, 108}, {115, 250, -33}, },
            {{65, 95, -24}, {97, 97, 109}, {98, 122, 62}, {192, 250, -24}, },
            {{0, 124, 110}, {125, 125, 111}, {126, 126, 112}, {127, 127, 113}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{48, 57, 114}, },
            {{46, 57, -18}, },
            {{48, 48, 115}, {49, 49, 116}, },
            {{48, 57, 117}, },
            {{45, 45, 118}, {48, 57, 119}, },
            {{45, 57, -57}, },
            {},
            {},
            {},
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 110, -27}, {111, 111, 120}, {112, 250, -27}, },
            {{65, 95, -24}, {97, 97, 121}, {98, 250, -37}, },
            {{65, 95, -24}, {97, 108, 62}, {109, 109, 122}, {110, 110, 123}, {111, 250, -29}, },
            {{65, 95, -24}, {97, 112, 62}, {113, 113, 124}, {114, 115, 62}, {116, 116, 125}, {117, 122, 62}, {192, 250, -24}, },
            {{65, 107, -28}, {108, 108, 126}, {109, 122, 62}, {192, 250, -24}, },
            {{65, 107, -28}, {108, 108, 127}, {109, 250, -100}, },
            {{65, 109, -29}, {110, 110, 128}, {111, 250, -29}, },
            {{65, 95, -24}, {97, 115, 62}, {116, 116, 129}, {117, 250, -99}, },
            {{65, 95, -24}, {97, 105, 62}, {106, 106, 130}, {107, 122, 62}, {192, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 110, -27}, {111, 111, 131}, {112, 250, -27}, },
            {{65, 95, -24}, {97, 97, 132}, {98, 250, -37}, },
            {{65, 109, -29}, {110, 110, 133}, {111, 250, -29}, },
            {{65, 113, -33}, {114, 114, 134}, {115, 250, -33}, },
            {{65, 95, -24}, {97, 116, 62}, {117, 117, 135}, {118, 250, -30}, },
            {{65, 113, -33}, {114, 114, 136}, {115, 250, -33}, },
            {{0, 127, -38}, },
            {},
            {{0, 127, -38}, },
            {{0, 127, -38}, },
            {{48, 57, 114}, },
            {{48, 49, -55}, },
            {{48, 49, -55}, },
            {{48, 57, 117}, {69, 101, -19}, },
            {{48, 57, 119}, },
            {{48, 57, 119}, },
            {{65, 107, -28}, {108, 108, 137}, {109, 250, -100}, },
            {{65, 95, -24}, {97, 114, 62}, {115, 115, 138}, {116, 122, 62}, {192, 250, -24}, },
            {{65, 100, -34}, {101, 101, 139}, {102, 250, -34}, },
            {{65, 114, -123}, {115, 115, 140}, {116, 250, -123}, },
            {{65, 116, -110}, {117, 117, 141}, {118, 250, -30}, },
            {{65, 218, -24}, {224, 226, 70}, {227, 227, 142}, {231, 250, -24}, },
            {{65, 114, -123}, {115, 115, 143}, {116, 250, -123}, },
            {{65, 95, -24}, {97, 103, 62}, {104, 104, 144}, {105, 122, 62}, {192, 250, -24}, },
            {{65, 227, -24}, {231, 231, 145}, {233, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 100, -34}, {101, 101, 146}, {102, 250, -34}, },
            {{65, 95, -24}, {97, 98, 62}, {99, 99, 147}, {100, 122, 62}, {192, 250, -24}, },
            {{65, 107, -28}, {108, 108, 148}, {109, 250, -100}, },
            {{65, 226, -127}, {227, 227, 149}, {231, 250, -24}, },
            {{65, 108, -98}, {109, 109, 150}, {110, 122, 62}, {192, 250, -24}, },
            {{65, 100, -34}, {101, 101, 151}, {102, 250, -34}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 114, -123}, {115, 115, 152}, {116, 250, -123}, },
            {{65, 227, -24}, {231, 231, 153}, {233, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 95, -24}, {97, 97, 154}, {98, 250, -37}, },
            {{65, 110, -27}, {111, 111, 155}, {112, 250, -27}, },
            {{65, 100, -34}, {101, 101, 156}, {102, 250, -34}, },
            {{65, 95, -24}, {97, 97, 157}, {98, 250, -37}, },
            {{65, 226, -127}, {227, 227, 158}, {231, 250, -24}, },
            {{65, 115, -103}, {116, 116, 159}, {117, 250, -99}, },
            {{65, 100, -34}, {101, 101, 160}, {102, 250, -34}, },
            {{65, 250, -24}, },
            {{65, 110, -27}, {111, 111, 161}, {112, 250, -27}, },
            {{65, 95, -24}, {97, 104, 62}, {105, 105, 162}, {106, 122, 62}, {192, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 100, -34}, {101, 101, 163}, {102, 250, -34}, },
            {{65, 95, -24}, {97, 97, 164}, {98, 250, -37}, },
            {{65, 109, -29}, {110, 110, 165}, {111, 250, -29}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{32, 32, 166}, {65, 250, -24}, },
            {{65, 110, -27}, {111, 111, 167}, {112, 250, -27}, },
            {{65, 110, -27}, {111, 111, 168}, {112, 250, -27}, },
            {{65, 95, -24}, {97, 99, 62}, {100, 100, 169}, {101, 122, 62}, {192, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 109, -29}, {110, 110, 170}, {111, 250, -29}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 115, -103}, {116, 116, 171}, {117, 250, -99}, },
            {{100, 100, 172}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 104, -152}, {105, 105, 173}, {106, 250, -152}, },
            {{65, 95, -24}, {97, 97, 174}, {98, 250, -37}, },
            {{65, 110, -27}, {111, 111, 175}, {112, 250, -27}, },
            {{97, 97, 176}, },
            {{65, 108, -98}, {109, 109, 177}, {110, 250, -136}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{32, 32, 178}, },
            {{65, 100, -34}, {101, 101, 179}, {102, 250, -34}, },
            {{99, 99, 180}, },
            {{65, 109, -29}, {110, 110, 181}, {111, 250, -29}, },
            {{108, 108, 182}, },
            {{65, 115, -103}, {116, 116, 183}, {117, 250, -99}, },
            {{97, 97, 184}, },
            {{65, 110, -27}, {111, 111, 185}, {112, 250, -27}, },
            {{115, 115, 186}, },
            {{65, 250, -24}, },
            {{115, 115, 187}, },
            {{101, 101, 188}, },
            {},
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 42, 42, 42, 42, 34, 31, 0, 16, 17, 29, 28, 7, 26, 23, 30, 40, 40, -1, 1, 33, 22, 38, 39, 38, 38, 38, 35, 38, 38, 38, 38, 38, 38, 38, 38, -1, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, -1, 40, -1, -1, -1, -1, 10, 32, 14, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 38, 38, 38, 38, 38, 38, 38, 38, 38, 36, 38, 38, 19, 38, 38, 38, -1, 37, -1, -1, 41, 40, 40, 41, -1, 41, 38, 38, 38, 38, 38, 38, 38, 38, 38, 11, 38, 38, 38, 38, 38, 38, 8, 12, 38, 38, 9, 38, 38, 38, 38, 38, 38, 38, 13, 38, 38, 24, 38, 38, 38, 27, 25, 38, 38, 38, 38, 20, 38, 2, 4, 38, -1, 18, 6, 38, 38, 38, -1, 38, 5, 21, -1, 38, -1, 38, -1, 38, -1, 38, -1, 15, -1, -1, 3, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
